#!/usr/bin/env bash
##=============================================================================
## Build-JamfTerraform.sh
## Generates Terraform main.tf + variables.tf from the title's macOS/Jamf
## JSON input files. Replaces Build-JamfTerraform.ps1 for Linux CI runners.
##
## Usage:
##   bash Build-JamfTerraform.sh \
##     --jamf-input-dir  macos/jamf \
##     --package-path    out/google-chrome-134.0.pkg \
##     --modules-dir     terraform-jamf-modules/modules \
##     --output-dir      tf-deploy
##
## Requires: bash, jq
##=============================================================================
set -euo pipefail

# ── Defaults ──────────────────────────────────────────────────────────────────
JAMF_INPUT_DIR="macos/jamf"
MAC_PACKAGE_YAML="macos/package.yaml"
PACKAGE_PATH=""
MODULES_DIR="terraform-jamf-modules/modules"
OUTPUT_DIR="tf-deploy"

# ── Parse arguments ──────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --jamf-input-dir)  JAMF_INPUT_DIR="$2";  shift 2 ;;
    --package-yaml)    MAC_PACKAGE_YAML="$2"; shift 2 ;;
    --package-path)    PACKAGE_PATH="$2";     shift 2 ;;
    --modules-dir)     MODULES_DIR="$2";      shift 2 ;;
    --output-dir)      OUTPUT_DIR="$2";       shift 2 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

# ── Verify inputs ────────────────────────────────────────────────────────────
for f in "$JAMF_INPUT_DIR/package-inputs.json" \
         "$JAMF_INPUT_DIR/policy-inputs.json" \
         "$JAMF_INPUT_DIR/scope-inputs.json"; do
  [[ -f "$f" ]] || { echo "❌ Required input file not found: $f"; exit 1; }
done

# ── Read JSON inputs via jq ──────────────────────────────────────────────────
PKG_JSON="$JAMF_INPUT_DIR/package-inputs.json"
POLICY_JSON="$JAMF_INPUT_DIR/policy-inputs.json"
SCOPE_JSON="$JAMF_INPUT_DIR/scope-inputs.json"

pkg_name=$(jq -r '.package_name // ""' "$PKG_JSON")
pkg_notes=$(jq -r '.notes // "Deployed by SPA pipeline"' "$PKG_JSON")
pkg_category_id=$(jq -r '.category_id // "-1"' "$PKG_JSON")
pkg_os_reqs=$(jq -r '.os_requirements // ""' "$PKG_JSON")
pkg_reboot=$(jq -r 'if .reboot_required == true then "true" else "false" end' "$PKG_JSON")

policy_name=$(jq -r '.policy_name // ""' "$POLICY_JSON")
policy_trigger=$(jq -r '.trigger // "RECURRING_CHECK_IN"' "$POLICY_JSON")
policy_freq=$(jq -r '.frequency // "Once per computer"' "$POLICY_JSON")
policy_enabled=$(jq -r 'if .enabled == false then "false" else "true" end' "$POLICY_JSON")
policy_recon=$(jq -r 'if .run_recon_after_install == false then "false" else "true" end' "$POLICY_JSON")
self_service_enabled=$(jq -r 'if .self_service_enabled == true then "true" else "false" end' "$POLICY_JSON")
ss_display_name=$(jq -r '.self_service_display_name // ""' "$POLICY_JSON")
ss_description=$(jq -r '.self_service_description // ""' "$POLICY_JSON")

# Scope group IDs → HCL list
scope_groups_hcl=$(jq -r '
  [.scope_groups.computer_groups // [] | .[] | select(. != null and (tostring | test("^[0-9]+$")))] |
  if length == 0 then "[]"
  else "[" + (map(tostring) | join(", ")) + "]"
  end' "$SCOPE_JSON")

exclusion_groups_hcl=$(jq -r '
  [.exclusion_groups.computer_groups // [] | .[] | select(. != null and (tostring | test("^[0-9]+$")))] |
  if length == 0 then "[]"
  else "[" + (map(tostring) | join(", ")) + "]"
  end' "$SCOPE_JSON")

# ── Read receipt_id from package.yaml ────────────────────────────────────────
receipt_id=""
if [[ -f "$MAC_PACKAGE_YAML" ]]; then
  receipt_id=$(grep -E '^\s*receipt_id:' "$MAC_PACKAGE_YAML" | head -1 | sed "s/.*receipt_id:\s*//" | tr -d "\"'" | xargs)
  echo "  Receipt ID: $receipt_id"
else
  echo "  ⚠ No package.yaml found — skipping extension attribute."
fi

# ── Resolve package file path ────────────────────────────────────────────────
if [[ -z "$PACKAGE_PATH" ]]; then
  PACKAGE_PATH=$(find out -type f \( -name '*.pkg' -o -name '*.dmg' \) 2>/dev/null | head -1)
  [[ -n "$PACKAGE_PATH" ]] || { echo "❌ No .pkg or .dmg found. Specify --package-path."; exit 1; }
fi

# ── Resolve absolute module path ─────────────────────────────────────────────
ABS_MODULES_DIR=$(cd "$MODULES_DIR" && pwd)

echo "Generating Terraform config for: $pkg_name"
echo "  Package: $PACKAGE_PATH"

# ── Generate main.tf ─────────────────────────────────────────────────────────
mkdir -p "$OUTPUT_DIR"

cat > "$OUTPUT_DIR/main.tf" <<TFEOF
##=============================================================================
## Auto-generated by SPA Build-JamfTerraform.sh — do not edit manually
##=============================================================================

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    jamfpro = {
      source  = "deploymenttheory/jamfpro"
      version = "~> 0.37"
    }
  }
  backend "http" {} # GitLab-managed Terraform state
}

provider "jamfpro" {
  jamfpro_instance_fqdn                = var.jamf_instance_url
  client_id                            = var.jamf_client_id
  client_secret                        = var.jamf_client_secret
  auth_method                          = "oauth2"
  jamfpro_load_balancer_lock           = false
  token_refresh_buffer_period_seconds  = 5
  mandatory_request_delay_milliseconds = 100
}

# ── Package ──────────────────────────────────────────────────────────────────
module "package" {
  source              = "${ABS_MODULES_DIR}/package"
  package_name        = "${pkg_name}"
  package_file_source = var.package_file_path
  category_id         = "${pkg_category_id}"
  notes               = "${pkg_notes}"
  os_requirements     = "${pkg_os_reqs}"
  reboot_required     = ${pkg_reboot}
}

# ── Policy ───────────────────────────────────────────────────────────────────
module "policy" {
  source                    = "${ABS_MODULES_DIR}/policy"
  policy_name               = "${policy_name}"
  package_id                = module.package.id
  category_id               = -1
  enabled                   = ${policy_enabled}
  trigger                   = "${policy_trigger}"
  frequency                 = "${policy_freq}"
  scope_group_ids           = ${scope_groups_hcl}
  exclusion_group_ids       = ${exclusion_groups_hcl}
  run_recon_after_install   = ${policy_recon}
  reboot_required           = ${pkg_reboot}
  self_service_enabled      = ${self_service_enabled}
  self_service_display_name = "${ss_display_name}"
  self_service_description  = "${ss_description}"
}

# ── Outputs ──────────────────────────────────────────────────────────────────
output "package_id" {
  value = module.package.id
}

output "policy_id" {
  value = module.policy.id
}
TFEOF

# ── Conditionally add Extension Attribute module ─────────────────────────────
if [[ -n "$receipt_id" && "$receipt_id" != "com.vendor.todo" ]]; then
  ea_name="SPA - ${pkg_name} Version"
  cat >> "$OUTPUT_DIR/main.tf" <<TFEOF

# ── Extension Attribute ──────────────────────────────────────────────────────
module "extension_attribute" {
  source     = "${ABS_MODULES_DIR}/extension-attribute"
  name       = "${ea_name}"
  receipt_id = "${receipt_id}"
}

output "extension_attribute_id" {
  value = module.extension_attribute.id
}
TFEOF
  echo "  ✅ Extension attribute module included (receipt: $receipt_id)"
else
  echo "  ⚠ No valid receipt_id — skipping extension attribute module."
fi

# ── Generate variables.tf ────────────────────────────────────────────────────
cat > "$OUTPUT_DIR/variables.tf" <<TFEOF
variable "jamf_instance_url" {
  type        = string
  description = "Jamf Pro instance FQDN (e.g. 'yourinstance.jamfcloud.com')."
}

variable "jamf_client_id" {
  type        = string
  sensitive   = true
  description = "Jamf Pro API client ID."
}

variable "jamf_client_secret" {
  type        = string
  sensitive   = true
  description = "Jamf Pro API client secret."
}

variable "package_file_path" {
  type        = string
  description = "Path to the .pkg or .dmg to upload."
}
TFEOF

echo "✅ Generated Terraform config in: $OUTPUT_DIR/"
echo "   main.tf      — package + policy modules"
echo "   variables.tf — provider credentials + package path"
