<#
.SYNOPSIS
  Generates a Terraform main.tf from the title's macos/jamf/*.json input files.

.DESCRIPTION
  Reads package-inputs.json, policy-inputs.json, and scope-inputs.json from the
  title repo, then generates a main.tf that wires up the terraform-jamf-modules.

  This script runs in the CI pipeline on a Linux runner before terraform apply.

.PARAMETER JamfInputDir
  Path to the macos/jamf/ directory containing the JSON input files.

.PARAMETER PackagePath
  Path to the .pkg or .dmg file to upload.

.PARAMETER ModulesDir
  Path to the cloned terraform-jamf-modules/modules/ directory.

.PARAMETER OutputDir
  Directory to write the generated main.tf and variables.tf into.
  Defaults to 'tf-deploy/'.

.EXAMPLE
  pwsh -File Build-JamfTerraform.ps1 `
      -JamfInputDir  macos/jamf `
      -PackagePath   out/google-chrome-134.0.pkg `
      -ModulesDir    terraform-jamf-modules/modules `
      -OutputDir     tf-deploy
#>
[CmdletBinding()]
param(
    [string] $JamfInputDir = 'macos/jamf',
    [string] $PackagePath  = '',
    [string] $ModulesDir   = 'terraform-jamf-modules/modules',
    [string] $OutputDir    = 'tf-deploy'
)

$ErrorActionPreference = 'Stop'

# ── Read JSON inputs ─────────────────────────────────────────────────────────
$pkgInputFile    = Join-Path $JamfInputDir 'package-inputs.json'
$policyInputFile = Join-Path $JamfInputDir 'policy-inputs.json'
$scopeInputFile  = Join-Path $JamfInputDir 'scope-inputs.json'

foreach ($f in @($pkgInputFile, $policyInputFile, $scopeInputFile)) {
    if (!(Test-Path $f)) { throw "Required input file not found: $f" }
}

$pkg    = Get-Content $pkgInputFile    -Raw | ConvertFrom-Json
$policy = Get-Content $policyInputFile -Raw | ConvertFrom-Json
$scope  = Get-Content $scopeInputFile  -Raw | ConvertFrom-Json

# ── Resolve package file path ─────────────────────────────────────────────────
if (-not $PackagePath) {
    # Try to find .pkg or .dmg in out/ directory
    $candidates = Get-ChildItem -Path 'out' -Include '*.pkg','*.dmg' -File -ErrorAction SilentlyContinue
    if ($candidates.Count -eq 1) {
        $PackagePath = $candidates[0].FullName
    } elseif ($candidates.Count -gt 1) {
        throw "Multiple package files found in out/. Specify -PackagePath explicitly."
    } else {
        throw "No .pkg or .dmg found in out/. Specify -PackagePath."
    }
}

Write-Host "Generating Terraform config for: $($pkg.package_name)" -ForegroundColor Cyan
Write-Host "  Package: $PackagePath" -ForegroundColor DarkCyan

# ── Build scope group IDs list ────────────────────────────────────────────────
$scopeGroupIds = @()
if ($scope.scope_groups -and $scope.scope_groups.computer_groups) {
    $scopeGroupIds = @($scope.scope_groups.computer_groups | Where-Object {
        $_ -and $_ -ne 'TODO-JAMF-SMART-GROUP-ID' -and $_ -match '^\d+$'
    })
}

$exclusionGroupIds = @()
if ($scope.exclusion_groups -and $scope.exclusion_groups.computer_groups) {
    $exclusionGroupIds = @($scope.exclusion_groups.computer_groups | Where-Object {
        $_ -and $_ -match '^\d+$'
    })
}

# ── Resolve module source paths ──────────────────────────────────────────────
$absModulesDir = (Resolve-Path $ModulesDir).Path

# ── Generate main.tf ─────────────────────────────────────────────────────────
$selfServiceEnabled = if ($policy.self_service_enabled -eq $true) { 'true' } else { 'false' }
$rebootRequired     = if ($pkg.reboot_required -eq $true) { 'true' } else { 'false' }
$reconAfterInstall  = if ($null -eq $policy.run_recon_after_install -or $policy.run_recon_after_install -eq $true) { 'true' } else { 'false' }
$policyEnabled      = if ($null -eq $policy.enabled -or $policy.enabled -eq $true) { 'true' } else { 'false' }

$scopeGroupsHcl = "[]"
if ($scopeGroupIds.Count -gt 0) {
    $scopeGroupsHcl = "[$(($scopeGroupIds -join ', '))]"
}

$exclusionGroupsHcl = "[]"
if ($exclusionGroupIds.Count -gt 0) {
    $exclusionGroupsHcl = "[$(($exclusionGroupIds -join ', '))]"
}

# Escape strings for HCL
function Escape-Hcl { param([string]$s) return $s -replace '"', '\"' }

$pkgName        = Escape-Hcl ($pkg.package_name ?? '')
$pkgNotes       = Escape-Hcl ($pkg.notes ?? 'Deployed by SPA pipeline')
$pkgCategory    = Escape-Hcl ($pkg.category_id ?? '-1')
$pkgOsReqs      = Escape-Hcl ($pkg.os_requirements ?? '')
$policyName     = Escape-Hcl ($policy.policy_name ?? '')
$policyTrigger  = Escape-Hcl ($policy.trigger ?? 'RECURRING_CHECK_IN')
$policyFreq     = Escape-Hcl ($policy.frequency ?? 'Once per computer')
$ssSelfName     = Escape-Hcl ($policy.self_service_display_name ?? '')
$ssDesc         = Escape-Hcl ($policy.self_service_description ?? '')

$mainTf = @"
##=============================================================================
## Auto-generated by SPA Build-JamfTerraform.ps1 — do not edit manually
##=============================================================================

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    jamfpro = {
      source  = "danjamf/jamfpro"
      version = "~> 0.16"
    }
  }
  backend "http" {} # GitLab-managed Terraform state
}

provider "jamfpro" {
  jamf_instance_fqdn = var.jamf_instance_url
  client_id          = var.jamf_client_id
  client_secret      = var.jamf_client_secret
  auth_method        = "oauth2"
}

# ── Package ──────────────────────────────────────────────────────────────────
module "package" {
  source              = "$absModulesDir/package"
  package_name        = "$pkgName"
  package_file_source = var.package_file_path
  category_id         = "$pkgCategory"
  notes               = "$pkgNotes"
  os_requirements     = "$pkgOsReqs"
  reboot_required     = $rebootRequired
}

# ── Policy ───────────────────────────────────────────────────────────────────
module "policy" {
  source                    = "$absModulesDir/policy"
  policy_name               = "$policyName"
  package_id                = module.package.id
  category_id               = -1
  enabled                   = $policyEnabled
  trigger                   = "$policyTrigger"
  frequency                 = "$policyFreq"
  scope_group_ids           = $scopeGroupsHcl
  exclusion_group_ids       = $exclusionGroupsHcl
  run_recon_after_install   = $reconAfterInstall
  reboot_required           = $rebootRequired
  self_service_enabled      = $selfServiceEnabled
  self_service_display_name = "$ssSelfName"
  self_service_description  = "$ssDesc"
}

# ── Outputs ──────────────────────────────────────────────────────────────────
output "package_id" {
  value = module.package.id
}

output "policy_id" {
  value = module.policy.id
}
"@

# ── Generate variables.tf ────────────────────────────────────────────────────
$variablesTf = @"
variable "jamf_instance_url" {
  type        = string
  description = "Jamf Pro instance FQDN (e.g. 'yourinstance.jamfcloud.com')."
}

variable "jamf_client_id" {
  type        = string
  sensitive   = true
  description = "Jamf Pro API client ID."
}

variable "jamf_client_secret" {
  type        = string
  sensitive   = true
  description = "Jamf Pro API client secret."
}

variable "package_file_path" {
  type        = string
  description = "Path to the .pkg or .dmg to upload."
}
"@

# ── Write output ──────────────────────────────────────────────────────────────
if (!(Test-Path $OutputDir)) {
    New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
}

Set-Content -Path (Join-Path $OutputDir 'main.tf')      -Value $mainTf      -Encoding utf8
Set-Content -Path (Join-Path $OutputDir 'variables.tf') -Value $variablesTf -Encoding utf8

Write-Host "✅ Generated Terraform config in: $OutputDir/" -ForegroundColor Green
Write-Host "   main.tf      — package + policy modules" -ForegroundColor DarkGray
Write-Host "   variables.tf — provider credentials + package path" -ForegroundColor DarkGray
