# 7-Zip 26.00.00 — Windows package definition
package_id: 7-zip
display_name: "7-Zip"
version: "26.00.00"
packaging_version: "1"
installer_type: msi
source_filename: 7z2601-x64.msi
max_install_time: 60

install_command: 'Invoke-AppDeployToolkit.exe'
uninstall_command: 'Invoke-AppDeployToolkit.exe -DeploymentType Uninstall'

detection_method: manual
detection_rules:
  - type: msi
    product_code: "{23170F69-40C1-2702-2601-000001000000}"
    version_operator: greaterThanOrEqual
    version: "26.00.00"

restart_behavior: basedOnReturnCode
install_experience: system

msi_information:
  product_code: "{23170F69-40C1-2702-2601-000001000000}"
  product_version: "26.01.00.0"
  product_name: "7-Zip 26.01 (x64 edition)"
  upgrade_code: "{23170F69-40C1-2702-0000-000004000000}"
  manufacturer: "Igor Pavlov"
