<#
.SYNOPSIS
    PK Protect - PSADT v4 deployment script.
    Generated by SPA Workbench on 2026-05-29.

.DESCRIPTION
    Performs Install, Uninstall, or Repair of PK Protect.
    Uses the PSAppDeployToolkit v4 function-based architecture.

.NOTES
    Framework : PSAppDeployToolkit 4.1.0
    Package   : pk-protect
    Version   : 20.35.0008
#>

[CmdletBinding()]
param
(
    [Parameter(Mandatory = $false)]
    [ValidateSet('Install', 'Uninstall', 'Repair')]
    [System.String]$DeploymentType,

    [Parameter(Mandatory = $false)]
    [ValidateSet('Auto', 'Interactive', 'NonInteractive', 'Silent')]
    [System.String]$DeployMode,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$SuppressRebootPassThru,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$TerminalServerMode,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$DisableLogging
)


##================================================
## MARK: Variables
##================================================

$adtSession = @{
    AppVendor              = 'PKWARE, Inc'
    AppName                = 'PK Protect'
    AppVersion             = '20.35.0008'
    AppArch                = 'x64'
    AppLang                = 'EN'
    AppRevision            = '01'
    AppSuccessExitCodes    = @(0)
    AppRebootExitCodes     = @(1641, 3010)
    AppProcessesToClose    = @('iexplore')
    AppScriptVersion       = '1.0.0'
    AppScriptDate          = '1/14/2026'
    AppScriptAuthor        = 'Shubham'
    RequireAdmin           = $true

    InstallName            = 'PKWARE_PKProtect_20.35.0008_v1.0'
    InstallTitle           = 'PKWARE_PKProtect_20.35.0008_v1.0'

    DeployAppScriptFriendlyName = $MyInvocation.MyCommand.Name
    DeployAppScriptParameters   = $PSBoundParameters
    DeployAppScriptVersion      = '4.1.0'
}


##================================================
## MARK: Deployment Flow
##================================================

function Install-ADTDeployment
{

    [CmdletBinding()]
    param
    (
    )

    ##================================================
    ## MARK: Pre-Install
    ##================================================
    $adtSession.InstallPhase = "Pre-$($adtSession.DeploymentType)"

        Show-ADTInstallationWelcome -CloseApps 'iexplore' -CloseAppsCountdown 60 -ForceCloseAppsCountdown 180
        Show-ADTInstallationProgress -StatusMessage 'Installation in Progress...' -WindowLocation 'TopCenter'
        # Raw PowerShell: PowerShell script block
                ## Show Welcome Message, close Internet Explorer if required, allow up to 3 deferrals, verify there is enough disk space to complete the install, and persist the prompt
        # Raw PowerShell: PowerShell script block
                ## Show Progress Message (with the default message)
        # Raw PowerShell: PowerShell script block
                ## <Perform Pre-Installation tasks here>
        Uninstall-ADTApplication -Name 'Smartcrypt' -ApplicationType 'MSI' -ErrorAction Stop
        Uninstall-ADTApplication -Name 'PK Protect' -ApplicationType 'MSI' -ErrorAction Stop
        $folderPath = 'C:\Users\*\AppData\Local\PKWARE'
        if (Test-Path -Path $folderPath) {
            Remove-Item -Path $folderPath -Force -Recurse
        }

    ##================================================
    ## MARK: Install
    ##================================================
    $adtSession.InstallPhase = $adtSession.DeploymentType

        # Raw PowerShell: PowerShell script block
                ## Handle Zero-Config MSI Installations
        # Raw PowerShell: Control flow block preserved as-is
        If ($useDefaultMsi) {
                    [Hashtable]$ExecuteDefaultMSISplat = @{ Action = 'Install'; Path = $defaultMsiFile }; If ($defaultMstFile) {
                        $ExecuteDefaultMSISplat.Add('Transform', $defaultMstFile)
                    }
                    Start-ADTMsiProcess @ExecuteDefaultMSISplat; If ($defaultMspFiles) {
                        $defaultMspFiles | ForEach-Object { Start-ADTMsiProcess -Action 'Patch' -Path $_ }
                    }
                }
        # Raw PowerShell: PowerShell script block
                ## <Perform Installation tasks here>
        Start-ADTMsiProcess -Action 'Install' -FilePath '$dirFiles\PK Protect 20.35.0008.msi' -ArgumentList 'GENCERT=1 SYSTEMAGENT=0 ALLUSERS=1 ARPNOREMOVE=1 MSIRESTARTMANAGER=1 MSIRESTARTMANAGERCONTROL=Disable MSIRMSHUTDOWN=2 ROOTDRIVE=C:\ MSIDISABLERMRESTART=Disable REBOOT=ReallySuppress /qn /norestart' -ErrorAction Stop
        Start-Sleep -Seconds 10

    ##================================================
    ## MARK: Post-Install
    ##================================================
    $adtSession.InstallPhase = "Post-$($adtSession.DeploymentType)"

        # Raw PowerShell: PowerShell script block
                ## <Perform Post-Installation tasks here>
        Remove-ADTRegistryKey -LiteralPath 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{EB7BF890-01AE-463C-96CB-A17A8F6DC678}' -Name 'URLUpdateInfo'
        Remove-ADTRegistryKey -LiteralPath 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{EB7BF890-01AE-463C-96CB-A17A8F6DC678}' -Name 'URLInfoAbout'
        Remove-ADTRegistryKey -LiteralPath 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{EB7BF890-01AE-463C-96CB-A17A8F6DC678}' -Name 'Helplink'
        Set-ADTRegistryKey -LiteralPath 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{EB7BF890-01AE-463C-96CB-A17A8F6DC678}' -Name 'NoModify' -Type 'String' -Value '1'
        Start-Sleep -Seconds 10
        # Raw PowerShell: PowerShell script block
        		$Check = (Get-ItemProperty -Path "HKLM:\SOFTWARE\PKWARE\Smartcrypt")
        # Raw PowerShell: Control flow block preserved as-is
        if(($Check.SMDS -ne "https://syxp2pscadm0001.ess.fiserv.one/mds") -OR ($Check.useIWA -ne "0") -OR ($Check.promptWithoutCredentials -ne "1") -OR ($Check.promptWithoutCredentialsInterval -ne "240")){
        
        			$agentPath = $env:ProgramFiles + '\PKWARE\Smartcrypt\agent.exe' # cmiller - made path dynamic
        			$discAgentPath = $env:ProgramFiles + '\PKWARE\Smartcrypt\DiscoveryAgent.exe'
        
        			# Update registry keys (replace "keyPath" and "keyValue" with actual values)
        			$keyPath1 = "HKLM:\Software\PKWARE\Smartcrypt" # cmiller - corrected path
        
        			# cmiller - Clean up existing registry settings in $keyPath1
        			Remove-ItemProperty -Path $keyPath1 -Name *
        
        			#$keyValue1 = "pkwareops.ess.fiserv.one/mds" # cmiller - need to change to a specific cluster node FQDN. Personal preference, I like to use https://
        			$keyValue1 = "https://syxp2pscadm0001.ess.fiserv.one/mds"
        
        			Set-ItemProperty -Path $keyPath1 -Name "SMDS" -Value $keyValue1
        			Set-ItemProperty -Path $keyPath1 -Name "useIWA" -Value "0"
        			Set-ItemProperty -Path $keyPath1 -Name "promptWithoutCredentials" -Value "1"
        			Set-ItemProperty -Path $keyPath1 -Name "promptWithoutCredentialsInterval" -Value "240"
        
        			Start-Process -FilePath $agentPath -NoNewWindow
        			Write-Log -Message "Registry settings have been applied, continue..."
        
        		}else{
        			#Already exists, do nothing...
        			Write-Log -Message "Registry settings already applied, continue..."
        		}
        # Raw PowerShell: Control flow block preserved as-is
        if(Test-Path -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\PKWare_PKProtect_17.60.0008_v1.0'){
        			Remove-ADTRegistryKey -Key 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\PKWare_PKProtect_17.60.0008_v1.0'
        		}
        # Raw PowerShell: PowerShell script block
                #Cleanup Desktop
        $folderPath = 'C:\Users\Public\Desktop\*PK Protect*'
        if (Test-Path -Path $folderPath) {
            Remove-Item -Path $folderPath -Force -Recurse
        }
        # Raw PowerShell: PowerShell script block
        		#Find App & PK Protect 20.35.0008 Uninstall Key
        
        		$appName = 'PK Protect 20.35.0008'
        
        		# Set registry keys to search
        		$registryUninstallx64 = 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall'
        		$registryUninstallx86 = 'HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall'
        		$regKeyList = $registryUninstallx86,$registryUninstallx64
        
        		# Grab info from registry
        		$returnList = (
        			$regKeyList |
        			ForEach{Get-ItemProperty ($_ + '\*')} |
        			Select PSChildName,
        					DisplayName,
        					Publisher,
        					DisplayVersion,
        					UninstallString,
        					DisplayIcon,
        					EstimatedSize,
        					Version,
        					InstallDate,
        					InstallLocation,
        					InstallSource,
        					ModifyPath,
        					PSPath |
        			Sort -Unique PSChildName
        		)
        		# Find matching apps by name
        		$foundApp = (
        			$returnList |
        			Where {$_.DisplayName -like ('*' + $AppName + '*')} |
        			Where {$_ -ne $null} #strip null entries
        		)
        
        		$ProdKey = ($foundApp).PSChildName
        
                $UninstallString = "MsiExec.exe /X $ProdKey"
        
        		$UninstallKey = ($FoundApp).PSPath
        
        		$Trim = $UninstallKey.TrimStart("Microsoft.PowerShell.Core\Registry::")
                $Replace = $trim -replace "HKEY_LOCAL_MACHINE", "HKLM:"
        
        		# If there were results
        # Raw PowerShell: Control flow block preserved as-is
        If ($foundApp){
        
                New-ItemProperty -Path $Replace -Name "UninstallString" -Value $UninstallString -Force
        		Write-Log -Message "Updated uninstall key to include uninstall string..."
        
        		}
}

function Uninstall-ADTDeployment
{
    [CmdletBinding()]
    param
    (
    )

    ##================================================
    ## MARK: Pre-Uninstall
    ##================================================
    $adtSession.InstallPhase = "Pre-$($adtSession.DeploymentType)"

        Show-ADTInstallationWelcome -CloseApps 'iexplore' -CloseAppsCountdown 60 -ForceCloseAppsCountdown 180
        Show-ADTInstallationProgress -StatusMessage 'Uninstall in Progress...' -WindowLocation 'TopCenter'
        # Raw PowerShell: PowerShell script block
                ## Show Welcome Message, close Internet Explorer with a 60 second countdown before automatically closing
        # Raw PowerShell: PowerShell script block
                ## Show Progress Message (with the default message)
        # Raw PowerShell: PowerShell script block
                ## <Perform Pre-Uninstallation tasks here>

    ##================================================
    ## MARK: Uninstall
    ##================================================
    $adtSession.InstallPhase = $adtSession.DeploymentType

        # Raw PowerShell: PowerShell script block
                ## Handle Zero-Config MSI Uninstallations
        # Raw PowerShell: Control flow block preserved as-is
        If ($useDefaultMsi) {
                    [Hashtable]$ExecuteDefaultMSISplat = @{ Action = 'Uninstall'; Path = $defaultMsiFile }; If ($defaultMstFile) {
                        $ExecuteDefaultMSISplat.Add('Transform', $defaultMstFile)
                    }
                    Start-ADTMsiProcess @ExecuteDefaultMSISplat
                }
        # Raw PowerShell: PowerShell script block
                ## <Perform Uninstallation tasks here>
        Uninstall-ADTApplication -Name 'PK Protect' -ApplicationType 'MSI' -ErrorAction Stop
        $folderPath = 'C:\Users\*\AppData\Local\PKWARE'
        if (Test-Path -Path $folderPath) {
            Remove-Item -Path $folderPath -Force -Recurse
        }

    ##================================================
    ## MARK: Post-Uninstall
    ##================================================
    $adtSession.InstallPhase = "Post-$($adtSession.DeploymentType)"

        # Raw PowerShell: PowerShell script block
                ## <Perform Post-Uninstallation tasks here>
}

function Repair-ADTDeployment
{
    [CmdletBinding()]
    param
    (
    )

    ##================================================
    ## MARK: Pre-Repair
    ##================================================
    $adtSession.InstallPhase = "Pre-$($adtSession.DeploymentType)"

        Show-ADTInstallationWelcome -CloseApps 'iexplore' -CloseAppsCountdown 60 -ForceCloseAppsCountdown 180
        Show-ADTInstallationProgress -StatusMessage 'Installation in Progress...' -WindowLocation 'TopCenter'
        # Raw PowerShell: PowerShell script block
                ## Show Welcome Message, close Internet Explorer if required, allow up to 3 deferrals, verify there is enough disk space to complete the install, and persist the prompt
        # Raw PowerShell: PowerShell script block
                ## Show Progress Message (with the default message)
        # Raw PowerShell: PowerShell script block
                ## <Perform Pre-Installation tasks here>
        Uninstall-ADTApplication -Name 'Smartcrypt' -ApplicationType 'MSI' -ErrorAction Stop
        Uninstall-ADTApplication -Name 'PK Protect' -ApplicationType 'MSI' -ErrorAction Stop
        $folderPath = 'C:\Users\*\AppData\Local\PKWARE'
        if (Test-Path -Path $folderPath) {
            Remove-Item -Path $folderPath -Force -Recurse
        }

    ##================================================
    ## MARK: Repair
    ##================================================
    $adtSession.InstallPhase = $adtSession.DeploymentType

        # Raw PowerShell: PowerShell script block
                ## Handle Zero-Config MSI Installations
        # Raw PowerShell: Control flow block preserved as-is
        If ($useDefaultMsi) {
                    [Hashtable]$ExecuteDefaultMSISplat = @{ Action = 'Install'; Path = $defaultMsiFile }; If ($defaultMstFile) {
                        $ExecuteDefaultMSISplat.Add('Transform', $defaultMstFile)
                    }
                    Start-ADTMsiProcess @ExecuteDefaultMSISplat; If ($defaultMspFiles) {
                        $defaultMspFiles | ForEach-Object { Start-ADTMsiProcess -Action 'Patch' -Path $_ }
                    }
                }
        # Raw PowerShell: PowerShell script block
                ## <Perform Installation tasks here>
        Start-ADTMsiProcess -Action 'Install' -FilePath '$dirFiles\PK Protect 20.35.0008.msi' -ArgumentList 'GENCERT=1 SYSTEMAGENT=0 ALLUSERS=1 ARPNOREMOVE=1 MSIRESTARTMANAGER=1 MSIRESTARTMANAGERCONTROL=Disable MSIRMSHUTDOWN=2 ROOTDRIVE=C:\ MSIDISABLERMRESTART=Disable REBOOT=ReallySuppress /qn /norestart' -ErrorAction Stop
        Start-Sleep -Seconds 10

    ##================================================
    ## MARK: Post-Repair
    ##================================================
    $adtSession.InstallPhase = "Post-$($adtSession.DeploymentType)"

        # Raw PowerShell: PowerShell script block
                ## <Perform Post-Installation tasks here>
        Remove-ADTRegistryKey -LiteralPath 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{EB7BF890-01AE-463C-96CB-A17A8F6DC678}' -Name 'URLUpdateInfo'
        Remove-ADTRegistryKey -LiteralPath 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{EB7BF890-01AE-463C-96CB-A17A8F6DC678}' -Name 'URLInfoAbout'
        Remove-ADTRegistryKey -LiteralPath 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{EB7BF890-01AE-463C-96CB-A17A8F6DC678}' -Name 'Helplink'
        Set-ADTRegistryKey -LiteralPath 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{EB7BF890-01AE-463C-96CB-A17A8F6DC678}' -Name 'NoModify' -Type 'String' -Value '1'
        Start-Sleep -Seconds 10
        # Raw PowerShell: PowerShell script block
        		$Check = (Get-ItemProperty -Path "HKLM:\SOFTWARE\PKWARE\Smartcrypt")
        # Raw PowerShell: Control flow block preserved as-is
        if(($Check.SMDS -ne "https://syxp2pscadm0001.ess.fiserv.one/mds") -OR ($Check.useIWA -ne "0") -OR ($Check.promptWithoutCredentials -ne "1") -OR ($Check.promptWithoutCredentialsInterval -ne "240")){
        
        			$agentPath = $env:ProgramFiles + '\PKWARE\Smartcrypt\agent.exe' # cmiller - made path dynamic
        			$discAgentPath = $env:ProgramFiles + '\PKWARE\Smartcrypt\DiscoveryAgent.exe'
        
        			# Update registry keys (replace "keyPath" and "keyValue" with actual values)
        			$keyPath1 = "HKLM:\Software\PKWARE\Smartcrypt" # cmiller - corrected path
        
        			# cmiller - Clean up existing registry settings in $keyPath1
        			Remove-ItemProperty -Path $keyPath1 -Name *
        
        			#$keyValue1 = "pkwareops.ess.fiserv.one/mds" # cmiller - need to change to a specific cluster node FQDN. Personal preference, I like to use https://
        			$keyValue1 = "https://syxp2pscadm0001.ess.fiserv.one/mds"
        
        			Set-ItemProperty -Path $keyPath1 -Name "SMDS" -Value $keyValue1
        			Set-ItemProperty -Path $keyPath1 -Name "useIWA" -Value "0"
        			Set-ItemProperty -Path $keyPath1 -Name "promptWithoutCredentials" -Value "1"
        			Set-ItemProperty -Path $keyPath1 -Name "promptWithoutCredentialsInterval" -Value "240"
        
        			Start-Process -FilePath $agentPath -NoNewWindow
        			Write-Log -Message "Registry settings have been applied, continue..."
        
        		}else{
        			#Already exists, do nothing...
        			Write-Log -Message "Registry settings already applied, continue..."
        		}
        # Raw PowerShell: Control flow block preserved as-is
        if(Test-Path -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\PKWare_PKProtect_17.60.0008_v1.0'){
        			Remove-ADTRegistryKey -Key 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\PKWare_PKProtect_17.60.0008_v1.0'
        		}
        # Raw PowerShell: PowerShell script block
                #Cleanup Desktop
        $folderPath = 'C:\Users\Public\Desktop\*PK Protect*'
        if (Test-Path -Path $folderPath) {
            Remove-Item -Path $folderPath -Force -Recurse
        }
        # Raw PowerShell: PowerShell script block
        		#Find App & PK Protect 20.35.0008 Uninstall Key
        
        		$appName = 'PK Protect 20.35.0008'
        
        		# Set registry keys to search
        		$registryUninstallx64 = 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall'
        		$registryUninstallx86 = 'HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall'
        		$regKeyList = $registryUninstallx86,$registryUninstallx64
        
        		# Grab info from registry
        		$returnList = (
        			$regKeyList |
        			ForEach{Get-ItemProperty ($_ + '\*')} |
        			Select PSChildName,
        					DisplayName,
        					Publisher,
        					DisplayVersion,
        					UninstallString,
        					DisplayIcon,
        					EstimatedSize,
        					Version,
        					InstallDate,
        					InstallLocation,
        					InstallSource,
        					ModifyPath,
        					PSPath |
        			Sort -Unique PSChildName
        		)
        		# Find matching apps by name
        		$foundApp = (
        			$returnList |
        			Where {$_.DisplayName -like ('*' + $AppName + '*')} |
        			Where {$_ -ne $null} #strip null entries
        		)
        
        		$ProdKey = ($foundApp).PSChildName
        
                $UninstallString = "MsiExec.exe /X $ProdKey"
        
        		$UninstallKey = ($FoundApp).PSPath
        
        		$Trim = $UninstallKey.TrimStart("Microsoft.PowerShell.Core\Registry::")
                $Replace = $trim -replace "HKEY_LOCAL_MACHINE", "HKLM:"
        
        		# If there were results
        # Raw PowerShell: Control flow block preserved as-is
        If ($foundApp){
        
                New-ItemProperty -Path $Replace -Name "UninstallString" -Value $UninstallString -Force
        		Write-Log -Message "Updated uninstall key to include uninstall string..."
        
        		}
}


##================================================
## MARK: Initialization
##================================================

$ErrorActionPreference = [System.Management.Automation.ActionPreference]::Stop
$ProgressPreference = [System.Management.Automation.ActionPreference]::SilentlyContinue
Set-StrictMode -Version 1

try
{
    if (Test-Path -LiteralPath "$PSScriptRoot\PSAppDeployToolkit\PSAppDeployToolkit.psd1" -PathType Leaf)
    {
        Get-ChildItem -LiteralPath "$PSScriptRoot\PSAppDeployToolkit" -Recurse -File | Unblock-File -ErrorAction Ignore
        Import-Module -FullyQualifiedName @{ ModuleName = "$PSScriptRoot\PSAppDeployToolkit\PSAppDeployToolkit.psd1"; Guid = '8c3c366b-8606-4576-9f2d-4051144f7ca2'; ModuleVersion = '4.1.0' } -Force
    }
    else
    {
        Import-Module -FullyQualifiedName @{ ModuleName = 'PSAppDeployToolkit'; Guid = '8c3c366b-8606-4576-9f2d-4051144f7ca2'; ModuleVersion = '4.1.0' } -Force
    }

    $iadtParams = Get-ADTBoundParametersAndDefaultValues -Invocation $MyInvocation
    $adtSession = Remove-ADTHashtableNullOrEmptyValues -Hashtable $adtSession
    $adtSession = Open-ADTSession @adtSession @iadtParams -PassThru
}
catch
{
    $Host.UI.WriteErrorLine((Out-String -InputObject $_ -Width ([System.Int32]::MaxValue)))
    exit 60008
}


##================================================
## MARK: Invocation
##================================================

try
{
    Get-ChildItem -LiteralPath $PSScriptRoot -Directory | & {
        process
        {
            if ($_.Name -match 'PSAppDeployToolkit\..+$')
            {
                Get-ChildItem -LiteralPath $_.FullName -Recurse -File | Unblock-File -ErrorAction Ignore
                Import-Module -Name $_.FullName -Force
            }
        }
    }

    & "$($adtSession.DeploymentType)-ADTDeployment"
    Close-ADTSession
}
catch
{
    $mainErrorMessage = "An unhandled error within [$($MyInvocation.MyCommand.Name)] has occurred.`n$(Resolve-ADTErrorRecord -ErrorRecord $_)"
    Write-ADTLogEntry -Message $mainErrorMessage -Severity 3
    Close-ADTSession -ExitCode 60001
}
