<#
.SYNOPSIS
    PK Protect - PSADT v4 deployment script.
    Generated by SPA Workbench on 2026-05-28.

.DESCRIPTION
    Performs Install, Uninstall, or Repair of PK Protect.
    Uses the PSAppDeployToolkit v4 function-based architecture.

.NOTES
    Framework : PSAppDeployToolkit 4.1.0
    Package   : pk-protect
    Version   : 20.35.0008
#>

[CmdletBinding()]
param
(
    [Parameter(Mandatory = $false)]
    [ValidateSet('Install', 'Uninstall', 'Repair')]
    [System.String]$DeploymentType,

    [Parameter(Mandatory = $false)]
    [ValidateSet('Auto', 'Interactive', 'NonInteractive', 'Silent')]
    [System.String]$DeployMode,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$SuppressRebootPassThru,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$TerminalServerMode,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$DisableLogging
)


##================================================
## MARK: Variables
##================================================

$adtSession = @{
    AppVendor              = 'PKWARE, Inc'
    AppName                = 'PK Protect'
    AppVersion             = '20.35.0008'
    AppArch                = 'x64'
    AppLang                = 'EN'
    AppRevision            = '01'
    AppSuccessExitCodes    = @(0)
    AppRebootExitCodes     = @(1641, 3010)
    AppProcessesToClose    = @()
    AppScriptVersion       = '1.0.0'
    AppScriptDate          = '2026-05-28'
    AppScriptAuthor        = 'SPA Factory'
    RequireAdmin           = $true

    InstallName            = 'PK Protect 20.35.0008'
    InstallTitle           = 'PK Protect 20.35.0008'

    DeployAppScriptFriendlyName = $MyInvocation.MyCommand.Name
    DeployAppScriptParameters   = $PSBoundParameters
    DeployAppScriptVersion      = '4.1.0'
    appVendor = 'PKWARE, Inc'
    appName = 'PK Protect'
    appVersion = '20.35.0008'
    appArch = 'x64'
    appLang = 'EN'
    appRevision = '01'
    appScriptVersion = '1.0.0'
    appScriptDate = '1/14/2026'
    appScriptAuthor = 'Shubham'
    installName = 'PKWARE_PKProtect_20.35.0008_v1.0'
    installTitle = 'PKWARE_PKProtect_20.35.0008_v1.0'
}

function Install-ADTDeployment
{
    [CmdletBinding()]
    param
    (
    )

    ##================================================
    ## MARK: Pre-Install
    ##================================================
    $adtSession.InstallPhase = "Pre-$($adtSession.DeploymentType)"

        Show-ADTInstallationProgress -StatusMessage 'Installation in Progress...' -WindowLocation 'TopCenter'
        Uninstall-ADTApplication -Name 'Smartcrypt' -ApplicationType 'MSI' -ErrorAction Stop
        Uninstall-ADTApplication -Name 'PK Protect' -ApplicationType 'MSI' -ErrorAction Stop
        $folderPath = 'C:\Users\*\AppData\Local\PKWARE'
        if (Test-Path -Path $folderPath) {
            Remove-Item -Path $folderPath -Force -Recurse
        }

    ##================================================
    ## MARK: Install
    ##================================================
    $adtSession.InstallPhase = $adtSession.DeploymentType

        Start-ADTMsiProcess -Action 'Install' -FilePath '$dirFiles\PK Protect 20.35.0008.msi' -ArgumentList 'GENCERT=1 SYSTEMAGENT=0 ALLUSERS=1 ARPNOREMOVE=1 MSIRESTARTMANAGER=1 MSIRESTARTMANAGERCONTROL=Disable MSIRMSHUTDOWN=2 ROOTDRIVE=C:\ MSIDISABLERMRESTART=Disable REBOOT=ReallySuppress /qn /norestart' -ErrorAction Stop
        Start-Sleep -Seconds 10

    ##================================================
    ## MARK: Post-Install
    ##================================================
    $adtSession.InstallPhase = "Post-$($adtSession.DeploymentType)"

        Remove-ADTRegistryKey -LiteralPath 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{EB7BF890-01AE-463C-96CB-A17A8F6DC678}' -Name 'URLUpdateInfo'
        Remove-ADTRegistryKey -LiteralPath 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{EB7BF890-01AE-463C-96CB-A17A8F6DC678}' -Name 'URLInfoAbout'
        Remove-ADTRegistryKey -LiteralPath 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{EB7BF890-01AE-463C-96CB-A17A8F6DC678}' -Name 'Helplink'
        Set-ADTRegistryKey -LiteralPath 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{EB7BF890-01AE-463C-96CB-A17A8F6DC678}' -Name 'NoModify' -Type 'String' -Value '1'
        Start-Sleep -Seconds 10
        Remove-ADTRegistryKey -LiteralPath '$keyPath1' -Name '*'
        Set-ADTRegistryKey -LiteralPath '$keyPath1' -Name 'SMDS' -Type 'String' -Value '$keyValue1'
        Set-ADTRegistryKey -LiteralPath '$keyPath1' -Name 'useIWA' -Type 'String' -Value '0'
        Set-ADTRegistryKey -LiteralPath '$keyPath1' -Name 'promptWithoutCredentials' -Type 'String' -Value '1'
        Set-ADTRegistryKey -LiteralPath '$keyPath1' -Name 'promptWithoutCredentialsInterval' -Type 'String' -Value '240'
        Start-ADTProcess -FilePath '$agentPath' -ErrorAction Stop
        Remove-ADTRegistryKey -LiteralPath 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\PKWare_PKProtect_17.60.0008_v1.0' -Name ''
        $folderPath = 'C:\Users\Public\Desktop\*PK Protect*'
        if (Test-Path -Path $folderPath) {
            Remove-Item -Path $folderPath -Force -Recurse
        }
        # Raw PowerShell: Could not be fully parsed — block preserved as-is
        ForEach{Get-ItemProperty ($_ + '\*')} |
        # Raw PowerShell: Could not be fully parsed — block preserved as-is
        If ($foundApp){
        
                New-ItemProperty -Path $Replace -Name "UninstallString" -Value $UninstallString -Force
        		Write-Log -Message "Updated uninstall key to include uninstall string..."
        
        		}
}

function Uninstall-ADTDeployment
{
    [CmdletBinding()]
    param
    (
    )

    ##================================================
    ## MARK: Pre-Uninstall
    ##================================================
    $adtSession.InstallPhase = "Pre-$($adtSession.DeploymentType)"

        Show-ADTInstallationProgress -StatusMessage 'Uninstall in Progress...' -WindowLocation 'TopCenter'

    ##================================================
    ## MARK: Uninstall
    ##================================================
    $adtSession.InstallPhase = $adtSession.DeploymentType

        Uninstall-ADTApplication -Name 'PK Protect' -ApplicationType 'MSI' -ErrorAction Stop
        $folderPath = 'C:\Users\*\AppData\Local\PKWARE'
        if (Test-Path -Path $folderPath) {
            Remove-Item -Path $folderPath -Force -Recurse
        }

    ##================================================
    ## MARK: Post-Uninstall
    ##================================================
    $adtSession.InstallPhase = "Post-$($adtSession.DeploymentType)"

        ## No post-uninstallation actions configured
}

function Repair-ADTDeployment
{
    [CmdletBinding()]
    param
    (
    )

    ##================================================
    ## MARK: Pre-Repair
    ##================================================
    $adtSession.InstallPhase = "Pre-$($adtSession.DeploymentType)"

        Show-ADTInstallationProgress -StatusMessage 'Installation in Progress...' -WindowLocation 'TopCenter'

    ##================================================
    ## MARK: Repair
    ##================================================
    $adtSession.InstallPhase = $adtSession.DeploymentType

        Write-ADTLogEntry -Message 'TODO: Add repair logic'

    ##================================================
    ## MARK: Post-Repair
    ##================================================
    $adtSession.InstallPhase = "Post-$($adtSession.DeploymentType)"

        ## No post-repair actions configured
}


##================================================
## MARK: Initialization
##================================================

$ErrorActionPreference = [System.Management.Automation.ActionPreference]::Stop
$ProgressPreference = [System.Management.Automation.ActionPreference]::SilentlyContinue
Set-StrictMode -Version 1

try
{
    if (Test-Path -LiteralPath "$PSScriptRoot\PSAppDeployToolkit\PSAppDeployToolkit.psd1" -PathType Leaf)
    {
        Get-ChildItem -LiteralPath "$PSScriptRoot\PSAppDeployToolkit" -Recurse -File | Unblock-File -ErrorAction Ignore
        Import-Module -FullyQualifiedName @{ ModuleName = "$PSScriptRoot\PSAppDeployToolkit\PSAppDeployToolkit.psd1"; Guid = '8c3c366b-8606-4576-9f2d-4051144f7ca2'; ModuleVersion = '4.1.0' } -Force
    }
    else
    {
        Import-Module -FullyQualifiedName @{ ModuleName = 'PSAppDeployToolkit'; Guid = '8c3c366b-8606-4576-9f2d-4051144f7ca2'; ModuleVersion = '4.1.0' } -Force
    }

    $iadtParams = Get-ADTBoundParametersAndDefaultValues -Invocation $MyInvocation
    $adtSession = Remove-ADTHashtableNullOrEmptyValues -Hashtable $adtSession
    $adtSession = Open-ADTSession @adtSession @iadtParams -PassThru
}
catch
{
    $Host.UI.WriteErrorLine((Out-String -InputObject $_ -Width ([System.Int32]::MaxValue)))
    exit 60008
}


##================================================
## MARK: Invocation
##================================================

try
{
    Get-ChildItem -LiteralPath $PSScriptRoot -Directory | & {
        process
        {
            if ($_.Name -match 'PSAppDeployToolkit\..+$')
            {
                Get-ChildItem -LiteralPath $_.FullName -Recurse -File | Unblock-File -ErrorAction Ignore
                Import-Module -Name $_.FullName -Force
            }
        }
    }

    & "$($adtSession.DeploymentType)-ADTDeployment"
    Close-ADTSession
}
catch
{
    $mainErrorMessage = "An unhandled error within [$($MyInvocation.MyCommand.Name)] has occurred.`n$(Resolve-ADTErrorRecord -ErrorRecord $_)"
    Write-ADTLogEntry -Message $mainErrorMessage -Severity 3
    Close-ADTSession -ExitCode 60001
}
