apiVersion: v1
kind: Service
metadata:
  name: spa-workbench
  namespace: spahost-dev-app
  labels:
    app: spa-workbench
    app.kubernetes.io/name: spa-workbench
    app.kubernetes.io/part-of: software-delivery-automation
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: spa-workbench
