<#
.SYNOPSIS
    Node.js - PSADT v4 deployment script.
    Generated by SPA New-Title scaffolding on 2026-04-20.

.DESCRIPTION
    Performs Install, Uninstall, or Repair of Node.js.
    Uses the PSAppDeployToolkit v4 function-based architecture.

.NOTES
    Framework : PSAppDeployToolkit 4.1.0
    Package   : node.js
    Version   : 25.8.1
#>

[CmdletBinding()]
param
(
    [Parameter(Mandatory = $false)]
    [ValidateSet('Install', 'Uninstall', 'Repair')]
    [System.String]$DeploymentType,

    [Parameter(Mandatory = $false)]
    [ValidateSet('Auto', 'Interactive', 'NonInteractive', 'Silent')]
    [System.String]$DeployMode,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$SuppressRebootPassThru,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$TerminalServerMode,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$DisableLogging
)


##================================================
## MARK: Variables
##================================================

$adtSession = @{
    AppVendor              = 'Node.js Foundation'
    AppName                = 'Node.js'
    AppVersion             = '25.8.1'
    AppArch                = 'x64'
    AppLang                = 'EN'
    AppRevision            = '01'
    AppSuccessExitCodes    = @(0)
    AppRebootExitCodes     = @(1641, 3010)
    AppProcessesToClose    = @()
    AppScriptVersion       = '1.0.0'
    AppScriptDate          = '2026-04-20'
    AppScriptAuthor        = 'SPA Factory'
    RequireAdmin           = $true

    InstallName            = 'Node.js 25.8.1'
    InstallTitle           = 'Node.js 25.8.1'

    DeployAppScriptFriendlyName = $MyInvocation.MyCommand.Name
    DeployAppScriptParameters   = $PSBoundParameters
    DeployAppScriptVersion      = '4.1.0'
}

function Install-ADTDeployment
{
    [CmdletBinding()]
    param
    (
    )

    ##================================================
    ## MARK: Pre-Install
    ##================================================
    $adtSession.InstallPhase = "Pre-$($adtSession.DeploymentType)"

        Show-ADTInstallationWelcome -CheckDiskSpace -AllowDefer -DeferTimes 3 -PersistPrompt

    ##================================================
    ## MARK: Install
    ##================================================
    $adtSession.InstallPhase = $adtSession.DeploymentType

        Start-ADTMsiProcess -Action 'Install' -FilePath 'node-v25.8.1-x64.msi' -ArgumentList '/QN /norestart' -ErrorAction Stop

    ##================================================
    ## MARK: Post-Install
    ##================================================
    $adtSession.InstallPhase = "Post-$($adtSession.DeploymentType)"

        # Write Fiserv registry detection marker
        Set-ADTRegistryKey -LiteralPath 'HKLM:\SOFTWARE\Fiserv\InstalledApps\node.js' `
            -Name 'Version' -Type 'String' -Value '25.8.1'
        Set-ADTRegistryKey -LiteralPath 'HKLM:\SOFTWARE\Fiserv\InstalledApps\node.js' `
            -Name 'Publisher' -Type 'String' -Value 'Node.js Foundation'
        Set-ADTRegistryKey -LiteralPath 'HKLM:\SOFTWARE\Fiserv\InstalledApps\node.js' `
            -Name 'DisplayName' -Type 'String' -Value 'Node.js'
        Set-ADTRegistryKey -LiteralPath 'HKLM:\SOFTWARE\Fiserv\InstalledApps\node.js' `
            -Name 'InstallDate' -Type 'String' -Value (Get-Date -Format 'yyyy-MM-dd')
}

function Uninstall-ADTDeployment
{
    [CmdletBinding()]
    param
    (
    )

    ##================================================
    ## MARK: Pre-Uninstall
    ##================================================
    $adtSession.InstallPhase = "Pre-$($adtSession.DeploymentType)"

        ## No pre-uninstallation actions configured

    ##================================================
    ## MARK: Uninstall
    ##================================================
    $adtSession.InstallPhase = $adtSession.DeploymentType

        Uninstall-ADTApplication -Name 'Node.js' -ApplicationType 'MSI' -ErrorAction Stop

    ##================================================
    ## MARK: Post-Uninstall
    ##================================================
    $adtSession.InstallPhase = "Post-$($adtSession.DeploymentType)"

        # Remove Fiserv registry detection marker
        Remove-ADTRegistryKey -LiteralPath 'HKLM:\SOFTWARE\Fiserv\InstalledApps\node.js'
}

function Repair-ADTDeployment
{
    [CmdletBinding()]
    param
    (
    )

    ##================================================
    ## MARK: Pre-Repair
    ##================================================
    $adtSession.InstallPhase = "Pre-$($adtSession.DeploymentType)"

        Show-ADTInstallationWelcome -CheckDiskSpace -AllowDefer -DeferTimes 3 -PersistPrompt

    ##================================================
    ## MARK: Repair
    ##================================================
    $adtSession.InstallPhase = $adtSession.DeploymentType

        Start-ADTMsiProcess -Action 'Install' -FilePath 'node-v25.8.1-x64.msi' -ArgumentList '/QN /norestart' -ErrorAction Stop

    ##================================================
    ## MARK: Post-Repair
    ##================================================
    $adtSession.InstallPhase = "Post-$($adtSession.DeploymentType)"

        # Write Fiserv registry detection marker
        Set-ADTRegistryKey -LiteralPath 'HKLM:\SOFTWARE\Fiserv\InstalledApps\node.js' `
            -Name 'Version' -Type 'String' -Value '25.8.1'
        Set-ADTRegistryKey -LiteralPath 'HKLM:\SOFTWARE\Fiserv\InstalledApps\node.js' `
            -Name 'Publisher' -Type 'String' -Value 'Node.js Foundation'
        Set-ADTRegistryKey -LiteralPath 'HKLM:\SOFTWARE\Fiserv\InstalledApps\node.js' `
            -Name 'DisplayName' -Type 'String' -Value 'Node.js'
        Set-ADTRegistryKey -LiteralPath 'HKLM:\SOFTWARE\Fiserv\InstalledApps\node.js' `
            -Name 'InstallDate' -Type 'String' -Value (Get-Date -Format 'yyyy-MM-dd')
}


##================================================
## MARK: Initialization
##================================================

$ErrorActionPreference = [System.Management.Automation.ActionPreference]::Stop
$ProgressPreference = [System.Management.Automation.ActionPreference]::SilentlyContinue
Set-StrictMode -Version 1

try
{
    if (Test-Path -LiteralPath "$PSScriptRoot\PSAppDeployToolkit\PSAppDeployToolkit.psd1" -PathType Leaf)
    {
        Get-ChildItem -LiteralPath "$PSScriptRoot\PSAppDeployToolkit" -Recurse -File | Unblock-File -ErrorAction Ignore
        Import-Module -FullyQualifiedName @{ ModuleName = "$PSScriptRoot\PSAppDeployToolkit\PSAppDeployToolkit.psd1"; Guid = '8c3c366b-8606-4576-9f2d-4051144f7ca2'; ModuleVersion = '4.1.0' } -Force
    }
    else
    {
        Import-Module -FullyQualifiedName @{ ModuleName = 'PSAppDeployToolkit'; Guid = '8c3c366b-8606-4576-9f2d-4051144f7ca2'; ModuleVersion = '4.1.0' } -Force
    }

    $iadtParams = Get-ADTBoundParametersAndDefaultValues -Invocation $MyInvocation
    $adtSession = Remove-ADTHashtableNullOrEmptyValues -Hashtable $adtSession
    $adtSession = Open-ADTSession @adtSession @iadtParams -PassThru
}
catch
{
    $Host.UI.WriteErrorLine((Out-String -InputObject $_ -Width ([System.Int32]::MaxValue)))
    exit 60008
}


##================================================
## MARK: Invocation
##================================================

try
{
    Get-ChildItem -LiteralPath $PSScriptRoot -Directory | & {
        process
        {
            if ($_.Name -match 'PSAppDeployToolkit\..+$')
            {
                Get-ChildItem -LiteralPath $_.FullName -Recurse -File | Unblock-File -ErrorAction Ignore
                Import-Module -Name $_.FullName -Force
            }
        }
    }

    & "$($adtSession.DeploymentType)-ADTDeployment"
    Close-ADTSession
}
catch
{
    $mainErrorMessage = "An unhandled error within [$($MyInvocation.MyCommand.Name)] has occurred.`n$(Resolve-ADTErrorRecord -ErrorRecord $_)"
    Write-ADTLogEntry -Message $mainErrorMessage -Severity 3
    Close-ADTSession -ExitCode 60001
}
