<#
.SYNOPSIS
    Terraform - PSADT v4 deployment script.
    Generated by SPA Workbench on 2026-06-03.

.DESCRIPTION
    Performs Install, Uninstall, or Repair of Terraform.
    Uses the PSAppDeployToolkit v4 function-based architecture.

.NOTES
    Framework : PSAppDeployToolkit 4.1.0
    Package   : terraform
    Version   : 1.5.7
#>

[CmdletBinding()]
param
(
    [Parameter(Mandatory = $false)]
    [ValidateSet('Install', 'Uninstall', 'Repair')]
    [System.String]$DeploymentType,

    [Parameter(Mandatory = $false)]
    [ValidateSet('Auto', 'Interactive', 'NonInteractive', 'Silent')]
    [System.String]$DeployMode,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$SuppressRebootPassThru,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$TerminalServerMode,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$DisableLogging
)

# ttt
##================================================
## MARK: Variables
##================================================

$adtSession = @{
    AppVendor              = 'HashiCorp'
    AppName                = 'Terraform'
    AppVersion             = '1.5.7'
    AppArch                = 'x64'
    AppLang                = 'EN'
    AppRevision            = '01'
    AppSuccessExitCodes    = @(0)
    AppRebootExitCodes     = @(1641, 3010)
    AppProcessesToClose    = @('Terraform')
    AppScriptVersion       = '1.0.0'
    AppScriptDate          = '29/09/2023'
    AppScriptAuthor        = 'Piyush Mishra'
    RequireAdmin           = $true

    InstallName            = ''
    InstallTitle           = ''

    DeployAppScriptFriendlyName = $MyInvocation.MyCommand.Name
    DeployAppScriptParameters   = $PSBoundParameters
    DeployAppScriptVersion      = '4.1.0'
}


##================================================
## MARK: Deployment Flow
##================================================

function Install-ADTDeployment
{

    [CmdletBinding()]
    param
    (
    )

    ##================================================
    ## MARK: Pre-Install
    ##================================================
    $adtSession.InstallPhase = "Pre-$($adtSession.DeploymentType)"

        Show-ADTInstallationWelcome -CloseApps 'Terraform' -CloseAppsCountdown 60 -ForceCloseAppsCountdown 180
        Show-ADTInstallationProgress -StatusMessage 'Installation in Progress...' -WindowLocation 'TopCenter'
        # <SPA:CustomCode Phase="Pre-Install" Guide="Enter custom pre-installation script code here (e.g. show welcome prompt, stop processes, check requirements)">
        # TODO: Enter custom pre-installation script code here (e.g. show welcome prompt, stop processes, check requirements)
        # </SPA:CustomCode>

    ##================================================
    ## MARK: Install
    ##================================================
    $adtSession.InstallPhase = $adtSession.DeploymentType

        # <SPA:Action Data="%7B%22type%22%3A%22raw_ps%22%2C%22desc%22%3A%22Control%20block%3A%20If%20(%24useDefaultMsi)%20%7B%22%2C%22script%22%3A%22If%20(%24useDefaultMsi)%20%7B%5Cn%5Ct%5Ct%5Ct%5Bhashtable%5D%24ExecuteDefaultMSISplat%20%3D%20%20%40%7B%20Action%20%3D%20'Install'%3B%20Path%20%3D%20%24defaultMsiFile%20%7D%3B%20If%20(%24defaultMstFile)%20%7B%20%24ExecuteDefaultMSISplat.Add('Transform'%2C%20%24defaultMstFile)%20%7D%5Cn%5Ct%5Ct%5Ct%7D%22%2C%22note%22%3A%22Control%20flow%20block%20preserved%20as-is%22%2C%22enabled%22%3Atrue%7D">
        # Raw PowerShell: Control flow block preserved as-is
        If ($useDefaultMsi) {
        			[hashtable]$ExecuteDefaultMSISplat =  @{ Action = 'Install'; Path = $defaultMsiFile }; If ($defaultMstFile) { $ExecuteDefaultMSISplat.Add('Transform', $defaultMstFile) }
        			}
        # </SPA:Action>
        # <SPA:Action Data="%7B%22type%22%3A%22raw_ps%22%2C%22desc%22%3A%22PowerShell%20block%3A%20%23%23%20%3CPerform%20Installation%20tasks%20here%3E%22%2C%22script%22%3A%22%5Ct%5Ct%23%23%20%3CPerform%20Installation%20tasks%20here%3E%5Cn%5Cn%20%20%20%20%20%20%20%5Cn%20%20%20%20%20%20%20%5Cn%20%20%20%20%20%20%20%24sourceFolder%20%3D%20%5C%22%24(%24adtSession.DirFiles)%5C%5CHashiCorp_Terraform_1.5.7%5C%22%5Cn%20%20%20%20%20%20%20%24destinationFolder%20%3D%20%5C%22C%3A%5C%5C%5C%22%22%2C%22note%22%3A%22PowerShell%20script%20block%22%2C%22enabled%22%3Atrue%7D">
        # Raw PowerShell: PowerShell script block
        		## <Perform Installation tasks here>
        
        
        
               $sourceFolder = "$($adtSession.DirFiles)\HashiCorp_Terraform_1.5.7"
               $destinationFolder = "C:\"
        # </SPA:Action>
        # <SPA:Action Data="%7B%22type%22%3A%22raw_ps%22%2C%22desc%22%3A%22Control%20block%3A%20if%20(Test-Path%20-Path%20%24destinationFolder%20-PathType%20Container)%20%22%2C%22script%22%3A%22if%20(Test-Path%20-Path%20%24destinationFolder%20-PathType%20Container)%20%7B%5Cn%20%20%20%20%20%20%20Copy-Item%20-Path%20%24sourceFolder%20-Destination%20%24destinationFolder%20-Recurse%20-Force%5Cn%20%20%20%20%20%20%20%7D%20else%20%7B%5Cn%20%20%20%20%20%20%20Copy-Item%20-Path%20%24sourceFolder%20-Destination%20%24destinationFolder%20-Recurse%7D%22%2C%22note%22%3A%22Control%20flow%20block%20preserved%20as-is%22%2C%22enabled%22%3Atrue%7D">
        # Raw PowerShell: Control flow block preserved as-is
        if (Test-Path -Path $destinationFolder -PathType Container) {
               Copy-Item -Path $sourceFolder -Destination $destinationFolder -Recurse -Force
               } else {
               Copy-Item -Path $sourceFolder -Destination $destinationFolder -Recurse}
        # </SPA:Action>
        # <SPA:CustomCode Phase="Install" Guide="Enter custom installation script code here (e.g. run MSI/EXE installer, perform file copy)">
        # TODO: Enter custom installation script code here (e.g. run MSI/EXE installer, perform file copy)
        # </SPA:CustomCode>

    ##================================================
    ## MARK: Post-Install
    ##================================================
    $adtSession.InstallPhase = "Post-$($adtSession.DeploymentType)"

        # <SPA:Action Data="%7B%22type%22%3A%22raw_ps%22%2C%22desc%22%3A%22PowerShell%20block%3A%20%23%23%20%3CPerform%20Post-Installation%20tasks%20here%3E%22%2C%22script%22%3A%22%5Ct%5Ct%23%23%20%3CPerform%20Post-Installation%20tasks%20here%3E%5Cn%20%20%20%20%5Cn%20%20%20%20%20%20%20%20%24variableName%20%3D%20%5C%22Path%5C%22%5Cn%20%20%20%20%20%20%20%20%24valueToAdd%20%3D%20%5C%22C%3A%5C%5CHashiCorp_Terraform_1.5.7%5C%22%5Cn%5Cn%20%5Cn%5Cn%20%20%20%20%20%20%20%20%24currentValue%20%3D%20%5BEnvironment%5D%3A%3AGetEnvironmentVariable(%24variableName%2C%20%5C%22Machine%5C%22)%5Cn%5Cn%20%20%20%20%20%20%20%20%24paths%20%3D%20%24ValueToAdd%20%2B%20%5C%22%3B%5C%22%20%2B%20%24currentValue%5Cn%5Cn%5Cn%20%20%20%20%20%20%20%20%5BEnvironment%5D%3A%3ASetEnvironmentVariable(%5C%22%24variableName%5C%22%2C%20%24paths%20%2C%5C%22Machine%5C%22)%22%2C%22note%22%3A%22PowerShell%20script%20block%22%2C%22enabled%22%3Atrue%7D">
        # Raw PowerShell: PowerShell script block
        		## <Perform Post-Installation tasks here>
        
                $variableName = "Path"
                $valueToAdd = "C:\HashiCorp_Terraform_1.5.7"
        
        
        
                $currentValue = [Environment]::GetEnvironmentVariable($variableName, "Machine")
        
                $paths = $ValueToAdd + ";" + $currentValue
        
        
                [Environment]::SetEnvironmentVariable("$variableName", $paths ,"Machine")
        # </SPA:Action>
        # <SPA:Action Data="%7B%22type%22%3A%22registry_set%22%2C%22desc%22%3A%22Registry%3A%20Application%20Name%20%3D%20Terraform%22%2C%22key%22%3A%22HKEY_LOCAL_MACHINE%5C%5CSOFTWARE%5C%5CFiserv%5C%5CApplications%5C%5CHashiCorp_Terraform_1.5.7%22%2C%22name%22%3A%22Application%20Name%22%2C%22value%22%3A%22Terraform%22%2C%22raw%22%3A%22Set-RegistryKey%20-Key%20%5C%22HKEY_LOCAL_MACHINE%5C%5CSOFTWARE%5C%5CFiserv%5C%5CApplications%5C%5CHashiCorp_Terraform_1.5.7%5C%22%20-Name%20'Application%20Name'%20-Value%20%5C%22Terraform%5C%22%20-Type%20String%22%2C%22enabled%22%3Atrue%7D">
        Set-ADTRegistryKey -LiteralPath 'HKEY_LOCAL_MACHINE\SOFTWARE\Fiserv\Applications\HashiCorp_Terraform_1.5.7' -Name 'Application Name' -Type 'String' -Value 'Terraform'
        # </SPA:Action>
        # <SPA:Action Data="%7B%22type%22%3A%22registry_set%22%2C%22desc%22%3A%22Registry%3A%20Manufacturer%20%3D%20HashiCorp%22%2C%22key%22%3A%22HKEY_LOCAL_MACHINE%5C%5CSOFTWARE%5C%5CFiserv%5C%5CApplications%5C%5CHashiCorp_Terraform_1.5.7%22%2C%22name%22%3A%22Manufacturer%22%2C%22value%22%3A%22HashiCorp%22%2C%22raw%22%3A%22Set-RegistryKey%20-Key%20%5C%22HKEY_LOCAL_MACHINE%5C%5CSOFTWARE%5C%5CFiserv%5C%5CApplications%5C%5CHashiCorp_Terraform_1.5.7%5C%22%20-Name%20'Manufacturer'%20-Value%20%5C%22HashiCorp%5C%22%20-Type%20String%22%2C%22enabled%22%3Atrue%7D">
        Set-ADTRegistryKey -LiteralPath 'HKEY_LOCAL_MACHINE\SOFTWARE\Fiserv\Applications\HashiCorp_Terraform_1.5.7' -Name 'Manufacturer' -Type 'String' -Value 'HashiCorp'
        # </SPA:Action>
        # <SPA:Action Data="%7B%22type%22%3A%22registry_set%22%2C%22desc%22%3A%22Registry%3A%20Install%20Date%20%3D%20%24value%22%2C%22key%22%3A%22HKEY_LOCAL_MACHINE%5C%5CSOFTWARE%5C%5CFiserv%5C%5CApplications%5C%5CHashiCorp_Terraform_1.5.7%22%2C%22name%22%3A%22Install%20Date%22%2C%22value%22%3A%22%24value%22%2C%22raw%22%3A%22Set-RegistryKey%20-Key%20%5C%22HKEY_LOCAL_MACHINE%5C%5CSOFTWARE%5C%5CFiserv%5C%5CApplications%5C%5CHashiCorp_Terraform_1.5.7%5C%22%20-Name%20'Install%20Date'%20-Value%20%5C%22%24value%5C%22%20-Type%20String%22%2C%22enabled%22%3Atrue%7D">
        Set-ADTRegistryKey -LiteralPath 'HKEY_LOCAL_MACHINE\SOFTWARE\Fiserv\Applications\HashiCorp_Terraform_1.5.7' -Name 'Install Date' -Type 'String' -Value '$value'
        # </SPA:Action>
        # <SPA:Action Data="%7B%22type%22%3A%22registry_set%22%2C%22desc%22%3A%22Registry%3A%20Version%20%3D%201.5.7%22%2C%22key%22%3A%22HKEY_LOCAL_MACHINE%5C%5CSOFTWARE%5C%5CFiserv%5C%5CApplications%5C%5CHashiCorp_Terraform_1.5.7%22%2C%22name%22%3A%22Version%22%2C%22value%22%3A%221.5.7%22%2C%22raw%22%3A%22Set-RegistryKey%20-Key%20%5C%22HKEY_LOCAL_MACHINE%5C%5CSOFTWARE%5C%5CFiserv%5C%5CApplications%5C%5CHashiCorp_Terraform_1.5.7%5C%22%20-Name%20'Version'%20-Value%20%5C%221.5.7%5C%22%20-Type%20String%22%2C%22enabled%22%3Atrue%7D">
        Set-ADTRegistryKey -LiteralPath 'HKEY_LOCAL_MACHINE\SOFTWARE\Fiserv\Applications\HashiCorp_Terraform_1.5.7' -Name 'Version' -Type 'String' -Value '1.5.7'
        # </SPA:Action>
        # <SPA:Action Data="%7B%22type%22%3A%22show_completion%22%2C%22desc%22%3A%22Show%20completion%20dialog%22%2C%22raw%22%3A%22%23%23%20If%20(-not%20%24useDefaultMsi)%20%7B%20Show-InstallationPrompt%20-Message%20'You%20can%20customize%20text%20to%20appear%20at%20the%20end%20of%20an%20install%20or%20remove%20it%20completely%20for%20unattended%20installations.'%20-ButtonRightText%20'OK'%20-Icon%20Information%20-NoWait%20%7D%22%2C%22enabled%22%3Atrue%7D">
        Show-ADTInstallationPrompt -Message 'The install has completed.' `
            -ButtonRightText 'OK' -Icon Information -NoWait -Timeout 5
        # </SPA:Action>
        # <SPA:CustomCode Phase="Post-Install" Guide="Enter custom post-installation script code here (e.g. apply registry keys, set environment variables, cleanup temporary files)">
        # TODO: Enter custom post-installation script code here (e.g. apply registry keys, set environment variables, cleanup temporary files)
        # </SPA:CustomCode>
}

function Uninstall-ADTDeployment
{
    [CmdletBinding()]
    param
    (
    )

    ##================================================
    ## MARK: Pre-Uninstall
    ##================================================
    $adtSession.InstallPhase = "Pre-$($adtSession.DeploymentType)"

        Show-ADTInstallationWelcome -CloseApps 'Terraform' -CloseAppsCountdown 60 -ForceCloseAppsCountdown 180
        Show-ADTInstallationProgress -StatusMessage 'Uninstall in Progress...' -WindowLocation 'TopCenter'
        # <SPA:CustomCode Phase="Pre-Uninstall" Guide="Enter custom pre-uninstallation script code here (e.g. show welcome prompt, close processes before uninstalling)">
        # TODO: Enter custom pre-uninstallation script code here (e.g. show welcome prompt, close processes before uninstalling)
        # </SPA:CustomCode>

    ##================================================
    ## MARK: Uninstall
    ##================================================
    $adtSession.InstallPhase = $adtSession.DeploymentType

        # <SPA:Action Data="%7B%22type%22%3A%22raw_ps%22%2C%22desc%22%3A%22Control%20block%3A%20If%20(%24useDefaultMsi)%20%7B%22%2C%22script%22%3A%22If%20(%24useDefaultMsi)%20%7B%5Cn%5Ct%5Ct%5Ct%5Bhashtable%5D%24ExecuteDefaultMSISplat%20%3D%20%20%40%7B%20Action%20%3D%20'Uninstall'%3B%20Path%20%3D%20%24defaultMsiFile%20%7D%3B%20If%20(%24defaultMstFile)%20%7B%20%24ExecuteDefaultMSISplat.Add('Transform'%2C%20%24defaultMstFile)%20%7D%5Cn%5Ct%5Ct%5CtStart-ADTMsiProcess%20%40ExecuteDefaultMSISplat%5Cn%5Ct%5Ct%7D%22%2C%22note%22%3A%22Control%20flow%20block%20preserved%20as-is%22%2C%22enabled%22%3Atrue%7D">
        # Raw PowerShell: Control flow block preserved as-is
        If ($useDefaultMsi) {
        			[hashtable]$ExecuteDefaultMSISplat =  @{ Action = 'Uninstall'; Path = $defaultMsiFile }; If ($defaultMstFile) { $ExecuteDefaultMSISplat.Add('Transform', $defaultMstFile) }
        			Start-ADTMsiProcess @ExecuteDefaultMSISplat
        		}
        # </SPA:Action>
        # <SPA:Action Data="%7B%22type%22%3A%22raw_ps%22%2C%22desc%22%3A%22PowerShell%20block%3A%20%23%20%3CPerform%20Uninstallation%20tasks%20here%3E%22%2C%22script%22%3A%22%5Ct%5Ct%23%20%3CPerform%20Uninstallation%20tasks%20here%3E%5Cn%5Cn%20%20%20%20%20%20%24folderPath%20%3D%20%5C%22C%3A%5C%5CHashiCorp_Terraform_1.5.7%5C%22%22%2C%22note%22%3A%22PowerShell%20script%20block%22%2C%22enabled%22%3Atrue%7D">
        # Raw PowerShell: PowerShell script block
        		# <Perform Uninstallation tasks here>
        
              $folderPath = "C:\HashiCorp_Terraform_1.5.7"
        # </SPA:Action>
        # <SPA:Action Data="%7B%22type%22%3A%22raw_ps%22%2C%22desc%22%3A%22Control%20block%3A%20if(Test-Path%20-Path%20%24folderPath%20-PathType%20Container)%22%2C%22script%22%3A%22if(Test-Path%20-Path%20%24folderPath%20-PathType%20Container)%5Cn%20%20%20%20%20%20%20%20%7B%5Cn%20%20%20%20%20%20%20%20Remove-Item%20-Path%20%24folderPath%20-Force%20-Recurse%7D%22%2C%22note%22%3A%22Control%20flow%20block%20preserved%20as-is%22%2C%22enabled%22%3Atrue%7D">
        # Raw PowerShell: Control flow block preserved as-is
        if(Test-Path -Path $folderPath -PathType Container)
                {
                Remove-Item -Path $folderPath -Force -Recurse}
        # </SPA:Action>
        # <SPA:CustomCode Phase="Uninstall" Guide="Enter custom uninstallation script code here (e.g. run MSI/EXE uninstall commands)">
        # TODO: Enter custom uninstallation script code here (e.g. run MSI/EXE uninstall commands)
        # </SPA:CustomCode>

    ##================================================
    ## MARK: Post-Uninstall
    ##================================================
    $adtSession.InstallPhase = "Post-$($adtSession.DeploymentType)"

        # <SPA:Action Data="%7B%22type%22%3A%22registry_remove%22%2C%22desc%22%3A%22Remove%20reg%3A%20HKEY_LOCAL_MACHINE%5C%5CSOFTWARE%5C%5CFiserv%5C%5CApplications%5C%5CHashiCorp_Terraform_1.5.7%22%2C%22key%22%3A%22HKEY_LOCAL_MACHINE%5C%5CSOFTWARE%5C%5CFiserv%5C%5CApplications%5C%5CHashiCorp_Terraform_1.5.7%22%2C%22name%22%3A%22%22%2C%22raw%22%3A%22Remove-RegistryKey%20-Key%20%5C%22HKEY_LOCAL_MACHINE%5C%5CSOFTWARE%5C%5CFiserv%5C%5CApplications%5C%5CHashiCorp_Terraform_1.5.7%5C%22%22%2C%22enabled%22%3Atrue%7D">
        Remove-ADTRegistryKey -LiteralPath 'HKEY_LOCAL_MACHINE\SOFTWARE\Fiserv\Applications\HashiCorp_Terraform_1.5.7' -Name ''
        # </SPA:Action>
        # <SPA:CustomCode Phase="Post-Uninstall" Guide="Enter custom post-uninstallation script code here (e.g. delete config folders, remove registry keys)">
        # TODO: Enter custom post-uninstallation script code here (e.g. delete config folders, remove registry keys)
        # </SPA:CustomCode>
}

function Repair-ADTDeployment
{
    [CmdletBinding()]
    param
    (
    )

    ##================================================
    ## MARK: Pre-Repair
    ##================================================
    $adtSession.InstallPhase = "Pre-$($adtSession.DeploymentType)"

        Show-ADTInstallationWelcome -CloseApps 'Terraform' -CloseAppsCountdown 60 -ForceCloseAppsCountdown 180
        Show-ADTInstallationProgress -StatusMessage 'Installation in Progress...' -WindowLocation 'TopCenter'
        # <SPA:CustomCode Phase="Pre-Install" Guide="Enter custom pre-installation script code here (e.g. show welcome prompt, stop processes, check requirements)">
        # TODO: Enter custom pre-installation script code here (e.g. show welcome prompt, stop processes, check requirements)
        # </SPA:CustomCode>

    ##================================================
    ## MARK: Repair
    ##================================================
    $adtSession.InstallPhase = $adtSession.DeploymentType

        # <SPA:Action Data="%7B%22type%22%3A%22raw_ps%22%2C%22desc%22%3A%22Control%20block%3A%20If%20(%24useDefaultMsi)%20%7B%22%2C%22script%22%3A%22If%20(%24useDefaultMsi)%20%7B%5Cn%5Ct%5Ct%5Ct%5Bhashtable%5D%24ExecuteDefaultMSISplat%20%3D%20%20%40%7B%20Action%20%3D%20'Install'%3B%20Path%20%3D%20%24defaultMsiFile%20%7D%3B%20If%20(%24defaultMstFile)%20%7B%20%24ExecuteDefaultMSISplat.Add('Transform'%2C%20%24defaultMstFile)%20%7D%5Cn%5Ct%5Ct%5Ct%7D%22%2C%22note%22%3A%22Control%20flow%20block%20preserved%20as-is%22%2C%22enabled%22%3Atrue%7D">
        # Raw PowerShell: Control flow block preserved as-is
        If ($useDefaultMsi) {
        			[hashtable]$ExecuteDefaultMSISplat =  @{ Action = 'Install'; Path = $defaultMsiFile }; If ($defaultMstFile) { $ExecuteDefaultMSISplat.Add('Transform', $defaultMstFile) }
        			}
        # </SPA:Action>
        # <SPA:Action Data="%7B%22type%22%3A%22raw_ps%22%2C%22desc%22%3A%22PowerShell%20block%3A%20%23%23%20%3CPerform%20Installation%20tasks%20here%3E%22%2C%22script%22%3A%22%5Ct%5Ct%23%23%20%3CPerform%20Installation%20tasks%20here%3E%5Cn%5Cn%20%20%20%20%20%20%20%5Cn%20%20%20%20%20%20%20%5Cn%20%20%20%20%20%20%20%24sourceFolder%20%3D%20%5C%22%24(%24adtSession.DirFiles)%5C%5CHashiCorp_Terraform_1.5.7%5C%22%5Cn%20%20%20%20%20%20%20%24destinationFolder%20%3D%20%5C%22C%3A%5C%5C%5C%22%22%2C%22note%22%3A%22PowerShell%20script%20block%22%2C%22enabled%22%3Atrue%7D">
        # Raw PowerShell: PowerShell script block
        		## <Perform Installation tasks here>
        
        
        
               $sourceFolder = "$($adtSession.DirFiles)\HashiCorp_Terraform_1.5.7"
               $destinationFolder = "C:\"
        # </SPA:Action>
        # <SPA:Action Data="%7B%22type%22%3A%22raw_ps%22%2C%22desc%22%3A%22Control%20block%3A%20if%20(Test-Path%20-Path%20%24destinationFolder%20-PathType%20Container)%20%22%2C%22script%22%3A%22if%20(Test-Path%20-Path%20%24destinationFolder%20-PathType%20Container)%20%7B%5Cn%20%20%20%20%20%20%20Copy-Item%20-Path%20%24sourceFolder%20-Destination%20%24destinationFolder%20-Recurse%20-Force%5Cn%20%20%20%20%20%20%20%7D%20else%20%7B%5Cn%20%20%20%20%20%20%20Copy-Item%20-Path%20%24sourceFolder%20-Destination%20%24destinationFolder%20-Recurse%7D%22%2C%22note%22%3A%22Control%20flow%20block%20preserved%20as-is%22%2C%22enabled%22%3Atrue%7D">
        # Raw PowerShell: Control flow block preserved as-is
        if (Test-Path -Path $destinationFolder -PathType Container) {
               Copy-Item -Path $sourceFolder -Destination $destinationFolder -Recurse -Force
               } else {
               Copy-Item -Path $sourceFolder -Destination $destinationFolder -Recurse}
        # </SPA:Action>
        # <SPA:CustomCode Phase="Install" Guide="Enter custom installation script code here (e.g. run MSI/EXE installer, perform file copy)">
        # TODO: Enter custom installation script code here (e.g. run MSI/EXE installer, perform file copy)
        # </SPA:CustomCode>

    ##================================================
    ## MARK: Post-Repair
    ##================================================
    $adtSession.InstallPhase = "Post-$($adtSession.DeploymentType)"

        # <SPA:Action Data="%7B%22type%22%3A%22raw_ps%22%2C%22desc%22%3A%22PowerShell%20block%3A%20%23%23%20%3CPerform%20Post-Installation%20tasks%20here%3E%22%2C%22script%22%3A%22%5Ct%5Ct%23%23%20%3CPerform%20Post-Installation%20tasks%20here%3E%5Cn%20%20%20%20%5Cn%20%20%20%20%20%20%20%20%24variableName%20%3D%20%5C%22Path%5C%22%5Cn%20%20%20%20%20%20%20%20%24valueToAdd%20%3D%20%5C%22C%3A%5C%5CHashiCorp_Terraform_1.5.7%5C%22%5Cn%5Cn%20%5Cn%5Cn%20%20%20%20%20%20%20%20%24currentValue%20%3D%20%5BEnvironment%5D%3A%3AGetEnvironmentVariable(%24variableName%2C%20%5C%22Machine%5C%22)%5Cn%5Cn%20%20%20%20%20%20%20%20%24paths%20%3D%20%24ValueToAdd%20%2B%20%5C%22%3B%5C%22%20%2B%20%24currentValue%5Cn%5Cn%5Cn%20%20%20%20%20%20%20%20%5BEnvironment%5D%3A%3ASetEnvironmentVariable(%5C%22%24variableName%5C%22%2C%20%24paths%20%2C%5C%22Machine%5C%22)%22%2C%22note%22%3A%22PowerShell%20script%20block%22%2C%22enabled%22%3Atrue%7D">
        # Raw PowerShell: PowerShell script block
        		## <Perform Post-Installation tasks here>
        
                $variableName = "Path"
                $valueToAdd = "C:\HashiCorp_Terraform_1.5.7"
        
        
        
                $currentValue = [Environment]::GetEnvironmentVariable($variableName, "Machine")
        
                $paths = $ValueToAdd + ";" + $currentValue
        
        
                [Environment]::SetEnvironmentVariable("$variableName", $paths ,"Machine")
        # </SPA:Action>
        # <SPA:Action Data="%7B%22type%22%3A%22registry_set%22%2C%22desc%22%3A%22Registry%3A%20Application%20Name%20%3D%20Terraform%22%2C%22key%22%3A%22HKEY_LOCAL_MACHINE%5C%5CSOFTWARE%5C%5CFiserv%5C%5CApplications%5C%5CHashiCorp_Terraform_1.5.7%22%2C%22name%22%3A%22Application%20Name%22%2C%22value%22%3A%22Terraform%22%2C%22raw%22%3A%22Set-RegistryKey%20-Key%20%5C%22HKEY_LOCAL_MACHINE%5C%5CSOFTWARE%5C%5CFiserv%5C%5CApplications%5C%5CHashiCorp_Terraform_1.5.7%5C%22%20-Name%20'Application%20Name'%20-Value%20%5C%22Terraform%5C%22%20-Type%20String%22%2C%22enabled%22%3Atrue%7D">
        Set-ADTRegistryKey -LiteralPath 'HKEY_LOCAL_MACHINE\SOFTWARE\Fiserv\Applications\HashiCorp_Terraform_1.5.7' -Name 'Application Name' -Type 'String' -Value 'Terraform'
        # </SPA:Action>
        # <SPA:Action Data="%7B%22type%22%3A%22registry_set%22%2C%22desc%22%3A%22Registry%3A%20Manufacturer%20%3D%20HashiCorp%22%2C%22key%22%3A%22HKEY_LOCAL_MACHINE%5C%5CSOFTWARE%5C%5CFiserv%5C%5CApplications%5C%5CHashiCorp_Terraform_1.5.7%22%2C%22name%22%3A%22Manufacturer%22%2C%22value%22%3A%22HashiCorp%22%2C%22raw%22%3A%22Set-RegistryKey%20-Key%20%5C%22HKEY_LOCAL_MACHINE%5C%5CSOFTWARE%5C%5CFiserv%5C%5CApplications%5C%5CHashiCorp_Terraform_1.5.7%5C%22%20-Name%20'Manufacturer'%20-Value%20%5C%22HashiCorp%5C%22%20-Type%20String%22%2C%22enabled%22%3Atrue%7D">
        Set-ADTRegistryKey -LiteralPath 'HKEY_LOCAL_MACHINE\SOFTWARE\Fiserv\Applications\HashiCorp_Terraform_1.5.7' -Name 'Manufacturer' -Type 'String' -Value 'HashiCorp'
        # </SPA:Action>
        # <SPA:Action Data="%7B%22type%22%3A%22registry_set%22%2C%22desc%22%3A%22Registry%3A%20Install%20Date%20%3D%20%24value%22%2C%22key%22%3A%22HKEY_LOCAL_MACHINE%5C%5CSOFTWARE%5C%5CFiserv%5C%5CApplications%5C%5CHashiCorp_Terraform_1.5.7%22%2C%22name%22%3A%22Install%20Date%22%2C%22value%22%3A%22%24value%22%2C%22raw%22%3A%22Set-RegistryKey%20-Key%20%5C%22HKEY_LOCAL_MACHINE%5C%5CSOFTWARE%5C%5CFiserv%5C%5CApplications%5C%5CHashiCorp_Terraform_1.5.7%5C%22%20-Name%20'Install%20Date'%20-Value%20%5C%22%24value%5C%22%20-Type%20String%22%2C%22enabled%22%3Atrue%7D">
        Set-ADTRegistryKey -LiteralPath 'HKEY_LOCAL_MACHINE\SOFTWARE\Fiserv\Applications\HashiCorp_Terraform_1.5.7' -Name 'Install Date' -Type 'String' -Value '$value'
        # </SPA:Action>
        # <SPA:Action Data="%7B%22type%22%3A%22registry_set%22%2C%22desc%22%3A%22Registry%3A%20Version%20%3D%201.5.7%22%2C%22key%22%3A%22HKEY_LOCAL_MACHINE%5C%5CSOFTWARE%5C%5CFiserv%5C%5CApplications%5C%5CHashiCorp_Terraform_1.5.7%22%2C%22name%22%3A%22Version%22%2C%22value%22%3A%221.5.7%22%2C%22raw%22%3A%22Set-RegistryKey%20-Key%20%5C%22HKEY_LOCAL_MACHINE%5C%5CSOFTWARE%5C%5CFiserv%5C%5CApplications%5C%5CHashiCorp_Terraform_1.5.7%5C%22%20-Name%20'Version'%20-Value%20%5C%221.5.7%5C%22%20-Type%20String%22%2C%22enabled%22%3Atrue%7D">
        Set-ADTRegistryKey -LiteralPath 'HKEY_LOCAL_MACHINE\SOFTWARE\Fiserv\Applications\HashiCorp_Terraform_1.5.7' -Name 'Version' -Type 'String' -Value '1.5.7'
        # </SPA:Action>
        # <SPA:Action Data="%7B%22type%22%3A%22show_completion%22%2C%22desc%22%3A%22Show%20completion%20dialog%22%2C%22raw%22%3A%22%23%23%20If%20(-not%20%24useDefaultMsi)%20%7B%20Show-InstallationPrompt%20-Message%20'You%20can%20customize%20text%20to%20appear%20at%20the%20end%20of%20an%20install%20or%20remove%20it%20completely%20for%20unattended%20installations.'%20-ButtonRightText%20'OK'%20-Icon%20Information%20-NoWait%20%7D%22%2C%22enabled%22%3Atrue%7D">
        Show-ADTInstallationPrompt -Message 'The install has completed.' `
            -ButtonRightText 'OK' -Icon Information -NoWait -Timeout 5
        # </SPA:Action>
        # <SPA:CustomCode Phase="Post-Install" Guide="Enter custom post-installation script code here (e.g. apply registry keys, set environment variables, cleanup temporary files)">
        # TODO: Enter custom post-installation script code here (e.g. apply registry keys, set environment variables, cleanup temporary files)
        # </SPA:CustomCode>
}


##================================================
## MARK: Initialization
##================================================

$ErrorActionPreference = [System.Management.Automation.ActionPreference]::Stop
$ProgressPreference = [System.Management.Automation.ActionPreference]::SilentlyContinue
Set-StrictMode -Version 1

try
{
    if (Test-Path -LiteralPath "$PSScriptRoot\PSAppDeployToolkit\PSAppDeployToolkit.psd1" -PathType Leaf)
    {
        Get-ChildItem -LiteralPath "$PSScriptRoot\PSAppDeployToolkit" -Recurse -File | Unblock-File -ErrorAction Ignore
        Import-Module -FullyQualifiedName @{ ModuleName = "$PSScriptRoot\PSAppDeployToolkit\PSAppDeployToolkit.psd1"; Guid = '8c3c366b-8606-4576-9f2d-4051144f7ca2'; ModuleVersion = '4.1.0' } -Force
    }
    else
    {
        Import-Module -FullyQualifiedName @{ ModuleName = 'PSAppDeployToolkit'; Guid = '8c3c366b-8606-4576-9f2d-4051144f7ca2'; ModuleVersion = '4.1.0' } -Force
    }

    $iadtParams = Get-ADTBoundParametersAndDefaultValues -Invocation $MyInvocation
    $adtSession = Remove-ADTHashtableNullOrEmptyValues -Hashtable $adtSession
    $adtSession = Open-ADTSession @adtSession @iadtParams -PassThru
}
catch
{
    $Host.UI.WriteErrorLine((Out-String -InputObject $_ -Width ([System.Int32]::MaxValue)))
    exit 60008
}


##================================================
## MARK: Invocation
##================================================

try
{
    Get-ChildItem -LiteralPath $PSScriptRoot -Directory | & {
        process
        {
            if ($_.Name -match 'PSAppDeployToolkit\..+$')
            {
                Get-ChildItem -LiteralPath $_.FullName -Recurse -File | Unblock-File -ErrorAction Ignore
                Import-Module -Name $_.FullName -Force
            }
        }
    }

    & "$($adtSession.DeploymentType)-ADTDeployment"
    Close-ADTSession
}
catch
{
    $mainErrorMessage = "An unhandled error within [$($MyInvocation.MyCommand.Name)] has occurred.`n$(Resolve-ADTErrorRecord -ErrorRecord $_)"
    Write-ADTLogEntry -Message $mainErrorMessage -Severity 3
    Close-ADTSession -ExitCode 60001
}
