include:
  - project: 'euc/software-package-automation/spa-frameworks/gitlab-ci-templates'
    ref: 'main'
    file:
      - 'templates/macos-deploy-jamf.yml'

stages:
  - deploy

variables:
  MACOS_ENABLED: "true"
  TF_JAMF_MODULES_REF: "main"
