include:
  - project: 'euc/software-package-automation/spa-frameworks/gitlab-ci-templates'
    ref: 'main'
    file:
      - 'templates/macos-deploy-jamf.yml'

stages:
  - build
  - deploy

variables:
  WINDOWS_ENABLED: "false"
  MACOS_ENABLED:   "true"
  PSADT_FRAMEWORK_VERSION: "4.1.0"
  MACOS_FRAMEWORK_VERSION: "1.0.0"
