<#
.SYNOPSIS
    Verint Desktop Messaging Client for NA - PSADT v4 deployment script.
    Generated by SPA Workbench on 2026-08-14.

.DESCRIPTION
    Performs Install, Uninstall, or Repair of Verint Desktop Messaging Client for NA.
    Uses the PSAppDeployToolkit v4 function-based architecture.

.NOTES
    Framework : PSAppDeployToolkit 4.1.8
    Package   : verint-desktop-messaging-client-for-na
    Version   : 15.2.9.178
#>

[CmdletBinding()]
param
(
    [Parameter(Mandatory = $false)]
    [ValidateSet('Install', 'Uninstall', 'Repair')]
    [System.String]$DeploymentType,

    [Parameter(Mandatory = $false)]
    [ValidateSet('Auto', 'Interactive', 'NonInteractive', 'Silent')]
    [System.String]$DeployMode,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$SuppressRebootPassThru,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$TerminalServerMode,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$DisableLogging
)


##================================================
## MARK: Variables
##================================================

$adtSession = @{
    AppVendor              = 'Verint'
    AppName                = 'VerintDesktopMessagingClientforNA'
    AppVersion             = '15.2.9.178'
    AppArch                = 'x64'
    AppLang                = 'EN'
    AppRevision            = '01'
    AppSuccessExitCodes    = @(0)
    AppRebootExitCodes     = @(1641, 3010)
    AppProcessesToClose    = @('aimtray', 'captureservice', 'wcapw32', 'wcapwlistener', 'verint.dms.connectionmanager', 'Verint.DPA.DCUWindowsService', 'Verint.DMS.DesktopMessagingClient', 'Verint.DPA.DCUBrowserService', 'captest', 'DCUApp', 'DpaWfoAlert', 'DPAMessageClient', 'LoggerManager', 'LoggerServer', 'LoggerServerMonitor', 'LoggerViewer', 'Gacutil', 'RegAsm', 'MsgPop', 'mspvdx', 'PopData', 'svstr', 'TSStart', 'java', 'javaw', 'jabswitch', 'java-rmi', 'javacpl', 'javaws', 'jp2launcher', 'jqs', 'keytool', 'kinit', 'klist', 'ktab', 'orbd', 'pack200', 'policytool', 'rmid', 'rmiregistry', 'servertool', 'ssvagent', 'tnameserv', 'unpack200')
    AppScriptVersion       = '1.0.0'
    AppScriptDate          = '09/29/2023'
    AppScriptAuthor        = 'EUC Packaging'
    RequireAdmin           = $true

    InstallName            = ''
    InstallTitle           = ''

    DeployAppScriptFriendlyName = $MyInvocation.MyCommand.Name
    DeployAppScriptParameters   = $PSBoundParameters
    DeployAppScriptVersion      = '4.1.8'
}


##================================================
## MARK: Deployment Flow
##================================================

function Install-ADTDeployment
{

    [CmdletBinding()]
    param
    (
    )

    ##================================================
    ## MARK: Pre-Install
    ##================================================
    $adtSession.InstallPhase = "Pre-$($adtSession.DeploymentType)"

        ## Show Welcome Message, close processes if specified, verify disk space, persist the prompt.
        $saiwParams = @{
            CheckDiskSpace = $true
            PersistPrompt = $true
        }
        if ($adtSession.AppProcessesToClose.Count -gt 0)
        {
            $saiwParams.Add('CloseProcesses', $adtSession.AppProcessesToClose)
        }
        Show-ADTInstallationWelcome @saiwParams
        ## Show Progress Message (with the default message).
        Show-ADTInstallationProgress -WindowLocation 'TopCenter'
        # Raw PowerShell: Control flow block preserved as-is
        If (Test-ADTServiceExists -Name "DCUBrowserService") {
        Stop-ADTServiceAndDependencies -Name "DCUBrowserService"
        }
        # Raw PowerShell: Control flow block preserved as-is
        If (Get-Process -Name 'DCUapp' -ErrorAction SilentlyContinue) {
        Start-ADTProcess -FilePath "TASKKILL" -ArgumentList "/F /IM DCUapp.exe /t" -WindowStyle Hidden
        Start-Sleep -Seconds 5
        }
        # Raw PowerShell: Control flow block preserved as-is
        If (Get-Process -Name 'DPAWow64' -ErrorAction SilentlyContinue) {
        Start-ADTProcess -FilePath "TASKKILL" -ArgumentList "/F /IM DPAWow64.exe /t" -WindowStyle Hidden
        Start-Sleep -Seconds 5
        }
        # Raw PowerShell: Control flow block preserved as-is
        If (Get-Process -Name 'svstr' -ErrorAction SilentlyContinue) {
        Start-ADTProcess -FilePath "TASKKILL" -ArgumentList "/F /IM svstr.exe /t" -WindowStyle Hidden
        Start-Sleep -Seconds 5
        }
        # Raw PowerShell: Control flow block preserved as-is
        If (Get-Process -Name 'DPAMessageClient' -ErrorAction SilentlyContinue) {
        Start-ADTProcess -FilePath "TASKKILL" -ArgumentList "/F /IM DPAMessageClient.exe /t" -WindowStyle Hidden
        Start-Sleep -Seconds 5
        }
        # Raw PowerShell: Control flow block preserved as-is
        If (Get-Process -Name 'CaptureService' -ErrorAction SilentlyContinue) {
        Start-ADTProcess -FilePath "TASKKILL" -ArgumentList "/F /IM CaptureService.exe /t" -WindowStyle Hidden
        Start-Sleep -Seconds 5
        }
        # Raw PowerShell: PowerShell script block
        ## Uninstall All Screen Capture Module Versions
        $ScreenCapture = Get-ADTApplication -Name 'Screen Capture Module' -NameMatch 'Exact'
        # Raw PowerShell: Control flow block preserved as-is
        If($ScreenCapture) {
            Write-ADTLogEntry -Message "Attempting to Removing Screen Capture Module."
        "{4F6241BF-B9B8-4439-8185-1D8FA52C1061}", <# 15.2.8.747 #>`
            "{BF4A5C34-57F2-4727-A1EB-359BD4BFEA8F}", <# 15.2.7.600 #>`
            "{8585ED5A-B7B3-4D27-85CF-105FD1E617F3}", <# 15.2.5.377 #>`
            "{AF86FAB8-F969-49C2-B0BD-0948E625248B}", <# 15.2 #>`
            "{E473C64C-48DF-4205-AE89-1093ABF80BEE}", <# 15.1 #>`
            "{ACF6A782-283F-474D-8EA4-F4A0D91A3B81}", <# 11 #>`
            "{F894CFF6-1501-43C1-8C51-69E769C4CD21}", <#  #>`
            "{3F69F2D9-FCB0-44F6-B4B9-61A82FD5A408}", <#  #>`
            "{DA905477-8428-49B7-A8F2-EC029CBAC023}" <#  #>`
                | ForEach-Object { Start-ADTMsiProcess -Action 'Uninstall' -FilePath "$_" } <# foreach item, uninstall #>
        }
        Uninstall-ADTApplication -Name 'Screen Capture Module' -NameMatch 'Exact' -ApplicationType 'MSI'
        # Raw PowerShell: PowerShell script block
                $RecheckScapture = Get-ADTApplication -Name 'Screen Capture Module' -NameMatch 'Exact'
        # Raw PowerShell: Control flow block preserved as-is
        If($RecheckScapture) {
            Write-ADTLogEntry -Message "Screen Capture Module Removal Failed."
        }
        Else {
            Write-ADTLogEntry -Message "Screen Capture Module Successfully Removed."
        }
        # Raw PowerShell: PowerShell script block
        ## Uninstall All Playback Versions
        $Playback = Get-ADTApplication -Name 'Playback' -NameMatch 'Exact'
        # Raw PowerShell: Control flow block preserved as-is
        If($Playback) {
        "{A7013F30-90A8-41C9-B6F1-7DDE49311B11}", <# 15.2.0.316 #>`
        "{FA98207B-3919-4A25-9CE8-80ADD7BAB7A7}", <# 15.2,0,300 #>`
        "{22B23068-FAAA-48EE-85F5-419C091C6333}", <# 15.2 #>`
        "{9717AA1A-3A0F-4488-A468-E5F6727FDAD2}", <# 15.1 #>`
        "{FEE25469-462E-4850-9C75-35D6BA91BC2C}", <# 11 #>`
        "{0F274A85-8973-4324-A1AB-3C32D39B9BA1}", <#  #>`
        "{6A140312-6A6F-434F-832D-A786F597989C}", <# #>`
        "{97024FA6-544F-4159-9067-C0AF13AC0F89}", <# #>`
        "{6ED181DA-F036-4734-A41D-1BEF909020F7}", <#  #>`
        "{7DB74931-8DDE-4F0D-8929-5E8294B79845}", <# #>`
        "{89EA4623-E4A6-4B10-A8C7-0C1FD8CE2EC1}" <# #>`
            | ForEach-Object { Start-ADTMsiProcess -Action 'Uninstall' -FilePath "$_" } <# foreach item, uninstall #>
        }
        Uninstall-ADTApplication -Name 'Playback' -NameMatch 'Exact' -ApplicationType 'MSI'
        # Raw PowerShell: PowerShell script block
                $RecheckPlayback = Get-ADTApplication -Name 'Playback' -NameMatch 'Exact'
        # Raw PowerShell: Control flow block preserved as-is
        If($RecheckPlayback) {
            Write-ADTLogEntry -Message "Playback Removal Failed."
        }
        Else {
            Write-ADTLogEntry -Message "Playback Successfully Removed."
        }
        # Raw PowerShell: PowerShell script block
        ## Uninstall All DPA Client Versions
        $DPAClient = Get-ADTApplication -Name 'Desktop & Process Analytics Client*' -NameMatch 'Wildcard'
        # Raw PowerShell: Control flow block preserved as-is
        If($DPAClient) {
        "{5EA14529-9A8B-4EC4-B19E-E343468CFBA5}", <# DPA x64 15.2.8.118 #>`
        "{8BA86C5A-6042-46E0-A1B8-0C9F79E56AA2}", <# DPA x32 15.2.8.118 #>`
            "{AF2463AC-FD42-41FC-99F6-BB27CB101E12}", <# DPA x64 15.2.7.124 #>`
            "{A582BE0B-B5FB-43A6-AE21-99FCBF6C2072}", <# DPA x32 15.2.7.124 #>`
            "{BC0DB85B-747E-4AB3-9C63-741BD660555B}", <# DPA x64 15.2.5 #>`
            "{0CD4B184-A8B9-4526-B128-2CD6E7DB1970}", <# DPA x32 15.2.5 #>`
            "{CBD809D8-724F-4F63-93BC-FD674F4ED711}", <# DPA x64 15.2.2.153 Process Discovery Plugin #>`
            "{CED814F5-781C-42C3-A621-162698063695}", <# 15.1 #>`
            "{5B87EDB6-6B7A-4AE7-BECF-23A3F4F7DF9B}",`
            "{A9ABACAE-393B-4A7B-A09A-616A19D54C6C}",<# DPA x64 15.2.2.153 #>`
            "{AF694898-4B4B-46E5-A2AA-8AE4B43E4A04}",<# DPA x64 15.2.9 #>`
            "{8DEF13F1-0A13-4116-8F45-43F84FCA955D}"<# DPA x64 15.2.9 #>`
                | ForEach-Object { Start-ADTMsiProcess -Action 'Uninstall' -FilePath "$_" } <# foreach item, uninstall #>
        }
        Uninstall-ADTApplication -Name 'Desktop & Process Analytics Client*' -NameMatch 'Wildcard' -ApplicationType 'MSI'
        # Raw PowerShell: PowerShell script block
                $RecheckDPAClient = Get-ADTApplication -Name 'Desktop & Process Analytics Client*' -NameMatch 'Wildcard'
        # Raw PowerShell: Control flow block preserved as-is
        If($RecheckDPAClient) {
            Write-ADTLogEntry -Message "DPA Client Removal Failed."
        }
        Else {
            Write-ADTLogEntry -Message "DPA Client Successfully Removed."
        }
        # Raw PowerShell: PowerShell script block
        ## Uninstall All Desktop Connection Manager Versions
        $DCManager = Get-ADTApplication -Name 'Desktop Messaging Connection Manager*' -NameMatch 'Wildcard'
        # Raw PowerShell: Control flow block preserved as-is
        If($DCManager) {
        "{21840FE9-B0B9-4282-9216-1ACE39764678}", <# 15.2.8.15 #>`
            "{FDFF1354-F27B-477E-BEE0-CB1407E5E6C2}", <# 15.2.7.14 #>`
            "{BD4B93DB-EFD0-4A09-997D-71543A0BE200}", <# 15.2.5 #>`
            "{8310EF63-CEB3-418A-9F49-7CE4E377F04D}", <# 15.2 #>`
            "{C9529B20-AF44-485B-8990-3C07A82D9B2E}" <# 15.1 #>`
                | ForEach-Object { Start-ADTMsiProcess -Action 'Uninstall' -FilePath "$_" } <# foreach item, uninstall #>
        }
        Uninstall-ADTApplication -Name 'Desktop Messaging Connection Manager*' -NameMatch 'Wildcard' -ApplicationType 'MSI'
        # Raw PowerShell: PowerShell script block
                $RecheckDCManager = Get-ADTApplication -Name 'Desktop Messaging Connection Manager*' -NameMatch 'Wildcard'
        # Raw PowerShell: Control flow block preserved as-is
        If($RecheckDCManager) {
            Write-ADTLogEntry -Message "Desktop Messaging Connection Manager Removal Failed."
        }
        Else {
            Write-ADTLogEntry -Message "Desktop Messaging Connection Manager Successfully Removed."
        }
        # Raw PowerShell: PowerShell script block
        ## Uninstall All Desktop Messaging Client Versions
        $DMClient = Get-ADTApplication -Name 'Desktop Messaging Client*' -NameMatch 'Wildcard'
        # Raw PowerShell: Control flow block preserved as-is
        If($DMClient) {
        "{44010D16-5431-4E4E-B596-725B68EA80FA}", <# 15.2.8.10 #>`
            "{09CD1FAA-BED3-4731-9398-6F422DBB122F}", <# 15.2.7.14 #>`
            "{9D7BD7C0-28F4-4509-A5CE-E215EC775ADA}", <# 15.2.5 #>`
            "{FD7A4C10-ED8E-40F2-9B49-1867D5962152}", <# 15.2 #>`
            "{009A24B5-2EEF-44D5-98D5-F710FD7D7BA9}", <#  #>`
            "{FC770B3D-FA18-44A0-938F-4B6D1260F7D0}" <# 15.1 #>`
                | ForEach-Object { Start-ADTMsiProcess -Action 'Uninstall' -FilePath "$_" } <# foreach item, uninstall #>
        }
        Uninstall-ADTApplication -Name 'Desktop Messaging Client*' -NameMatch 'Wildcard' -ApplicationType 'MSI'
        # Raw PowerShell: PowerShell script block
                $RecheckDMClient = Get-ADTApplication -Name 'Desktop Messaging Client*' -NameMatch 'Wildcard'
        # Raw PowerShell: Control flow block preserved as-is
        If($RecheckDMClient) {
            Write-ADTLogEntry -Message "Desktop Messaging Client Removal Failed."
        }
        Else {
            Write-ADTLogEntry -Message "Desktop Messaging Client Successfully Removed."
        }
        # Raw PowerShell: PowerShell script block
        ## Uninstall All Verint Logger Versions
        $VLogger = Get-ADTApplication -Name 'Logger' -NameMatch 'Exact'
        # Raw PowerShell: Control flow block preserved as-is
        If($VLogger) {
        "{2A55E493-F199-4888-807A-9DA554A92DED}", <# 15.2.4.74 #>`
        "{5BC0BD43-6B95-43CF-960D-D30670370E2C}" <# 15.1 #>`
            | ForEach-Object { Start-ADTMsiProcess -Action 'Uninstall' -FilePath "$_" } <# foreach item, uninstall #>
        }
        Uninstall-ADTApplication -Name 'Logger' -NameMatch 'Exact' -ApplicationType 'MSI'
        # Raw PowerShell: PowerShell script block
                $RecheckVLogger = Get-ADTApplication -Name 'Logger' -NameMatch 'Exact'
        # Raw PowerShell: Control flow block preserved as-is
        If($RecheckVLogger) {
            Write-ADTLogEntry -Message "Verint Logger Removal Failed."
        }
        Else {
            Write-ADTLogEntry -Message "Verint Logger Successfully Removed."
        }
        # Raw PowerShell: PowerShell script block
        ## Uninstall All Desktop Resources Versions
        $DResources = Get-ADTApplication -Name 'Desktop Resources Verint' -NameMatch 'Exact'
        # Raw PowerShell: Control flow block preserved as-is
        If($DResources) {
        "{2897355D-DFC1-423F-8734-26AB9A6F2483}", <# 15.2.8.14 #>`
            "{51801F63-2D4C-45FD-8CD0-D2F7385D08A8}", <# 15.2.7.15 #>`
            "{E353C20E-5F8D-47C8-81ED-54BC60585B93}", <# 15.2 #>`
            "{9FAE0F49-CBFE-47A7-8C50-767A4273996B}", <# 15.1 #>`
            "{27538D70-AE44-4CF0-ABFB-2A465C930F35}", <# 11.0 #>`
            "{4F6241BF-B9B8-4439-8185-1D8FA52C1061}" <# 15.2.8.747 #>`
                | ForEach-Object { Start-ADTMsiProcess -Action 'Uninstall' -FilePath "$_" } <# foreach item, uninstall #>
        }
        Uninstall-ADTApplication -Name 'Desktop Resources Verint' -NameMatch 'Exact' -ApplicationType 'MSI'
        # Raw PowerShell: PowerShell script block
                $RecheckDResources = Get-ADTApplication -Name 'Desktop Resources Verint' -NameMatch 'Exact'
        # Raw PowerShell: Control flow block preserved as-is
        If($RecheckDResources) {
            Write-ADTLogEntry -Message "Desktop Resources Verint Removal Failed."
        }
        Else {
            Write-ADTLogEntry -Message "Desktop Resources Verint Successfully Removed."
        }
        # Raw PowerShell: PowerShell script block
        ## Enable Microsoft Messaging Queue Service (MSMQ) for DPA, if disabled
        $InstallState = Get-WmiObject -query "select * from Win32_OptionalFeature where name = 'MSMQ-Container'"
        # Raw PowerShell: Control flow block preserved as-is
        If ($InstallState.InstallState -ne "1") {
         Write-ADTLogEntry -Message "Enabling MSMQ-Container feature"
         If ($envOSName -match "Windows 10") {
             Enable-WindowsOptionalFeature -Online -FeatureName "MSMQ-Container" -Source "SourcePath" -NoRestart
         }
         If ($envOSName -match "Windows 11") {
             Enable-WindowsOptionalFeature -Online -FeatureName "MSMQ-Container" -Source "SourcePath" -NoRestart
         }
        ## Wait-Process -Name "Dism"
        }
        # Raw PowerShell: PowerShell script block
                $InstallState = Get-WmiObject -query "select * from Win32_OptionalFeature where name = 'MSMQ-Server'"
        # Raw PowerShell: Control flow block preserved as-is
        If ($InstallState.InstallState -ne "1") {
         Write-ADTLogEntry -Message "Enabling MSMQ-Server feature"
         If ($envOSName -match "Windows 10") {
             Enable-WindowsOptionalFeature -Online -FeatureName "MSMQ-Server" -Source "SourcePath" -NoRestart
         }
        If ($envOSName -match "Windows 11") {
            Enable-WindowsOptionalFeature -Online -FeatureName "MSMQ-Server" -Source "SourcePath" -NoRestart
         }
         Wait-Process -Name "Dism"
        }
        # Raw PowerShell: PowerShell script block
                $InstallState = Get-WmiObject -query "select * from Win32_OptionalFeature where name = 'MSMQ-ADIntegration'"
        # Raw PowerShell: Control flow block preserved as-is
        If ($InstallState.InstallState -ne "1") {
        Write-ADTLogEntry -Message "Enabling MSMQ-ADIntegration feature"
        If ($envOSName -match "Windows 10") {
            Enable-WindowsOptionalFeature -Online -FeatureName "MSMQ-ADIntegration" -Source "SourcePath" -NoRestart
        }
        If ($envOSName -match "Windows 11") {
            Enable-WindowsOptionalFeature -Online -FeatureName "MSMQ-ADIntegration" -Source "SourcePath" -NoRestart
        }
        }
        # Raw PowerShell: Control flow block preserved as-is
        If ($Is64Bit) {
        If (-not (Test-Path -Path "$envProgramFilesX86\MSXML 4.0")) {
            Write-ADTLogEntry -Message "MSXML 4.0 not detected. Installing."
            Start-ADTMsiProcess -Action 'Install' -FilePath "$($adtSession.DirSupportFiles)\MSXML4\msxml.msi" -ArgumentList '/qn ALLUSERS=1 REBOOT=ReallySuppress'
        }
        }
        # Raw PowerShell: Control flow block preserved as-is
        If (-not (Test-Path -Path "$envProgramFiles\MSXML 4.0")) {
        Write-ADTLogEntry -Message "MSXML 4.0 not detected. Installing."
        Start-ADTMsiProcess -Action 'Install' -FilePath "$($adtSession.DirSupportFiles)\MSXML4\msxml.msi" -ArgumentList '/qn ALLUSERS=1 REBOOT=ReallySuppress'
        }
        # Raw PowerShell: Control flow block preserved as-is
        If ($Is64Bit) {
        If (-not (Test-Path -Path "HKEY_LOCAL_MACHINE\Software\Classes\Installer\Products\67D6ECF5CD5FBA732B8B22BAC8DE1B4D")) {
            Write-ADTLogEntry -Message "Visual C++ 2008 x64 not detected. Installing."
            Start-ADTProcess -FilePath "$($adtSession.DirSupportFiles)\Visual C++ 2008\vcredist_x64.exe" -ArgumentList "/q:a /c:`"msiexec.exe /i vcredist.msi /qn`"" -IgnoreExitCodes "1638" -ErrorAction SilentlyContinue
        }
        }
        # Raw PowerShell: Control flow block preserved as-is
        If (-not (Test-Path -Path "HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Products\6E815EB96CCE9A53884E7857C57002F0")) {
        Write-ADTLogEntry -Message "Visual C++ 2008 x86 not detected. Installing."
        Start-ADTProcess -FilePath "$($adtSession.DirSupportFiles)\Visual C++ 2008\vcredist_x86.exe" -ArgumentList "/q:a /c:`"msiexec.exe /i vcredist.msi /qn`"" -IgnoreExitCodes "1638" -ErrorAction SilentlyContinue
        }
        # Raw PowerShell: Control flow block preserved as-is
        If ($Is64Bit) {
        If (-not (Test-Path -Path "HKEY_LOCAL_MACHINE\Software\Classes\Installer\Products\1926E8D15D0BCE53481466615F760A7F")) {
            Write-ADTLogEntry -Message "Visual C++ 2010 x64 not detected. Installing."
            Start-ADTProcess -FilePath "$($adtSession.DirSupportFiles)\Visual C++ 2010\vcredist_x64.exe" -ArgumentList "/q /norestart" -IgnoreExitCodes "1638" -ErrorAction SilentlyContinue
        }
        }
        # Raw PowerShell: Control flow block preserved as-is
        If (-not (Test-Path -Path "HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Products\1D5E3C0FEDA1E123187686FED06E995A")) {
        Write-ADTLogEntry -Message "Visual C++ 2010 x86 not detected. Installing."
        Start-ADTProcess -FilePath "$($adtSession.DirSupportFiles)\Visual C++ 2010\vcredist_x86.exe" -ArgumentList "/q /norestart" -IgnoreExitCodes "1638" -ErrorAction SilentlyContinue
        }
        # Raw PowerShell: Control flow block preserved as-is
        If ($Is64Bit) {
        If (-not (Test-Path -Path "HKEY_LOCAL_MACHINE\Software\Classes\Installer\Dependencies\{ca67548a-5ebe-413a-b50c-4b9ceb6d66c6}")) {
            Write-ADTLogEntry -Message "Visual C++ 2012 x64 not detected. Installing."
            Start-ADTProcess -FilePath "$($adtSession.DirSupportFiles)\Visual C++ 2012\vcredist_x64.exe" -ArgumentList "/q /norestart" -IgnoreExitCodes "1638" -ErrorAction SilentlyContinue
        }
        }
        # Raw PowerShell: Control flow block preserved as-is
        If (-not (Test-Path -Path "HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Dependencies\{33d1fd90-4274-48a1-9bc1-97e33d9c2d6f}")) {
        Write-ADTLogEntry -Message "Visual C++ 2012 x86 not detected. Installing."
        Start-ADTProcess -FilePath "$($adtSession.DirSupportFiles)\Visual C++ 2012\vcredist_x86.exe" -ArgumentList "/q /norestart" -IgnoreExitCodes "1638" -ErrorAction SilentlyContinue
        }
        # Raw PowerShell: Control flow block preserved as-is
        If ($Is64Bit) {
        If (-not (Test-Path -Path "HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Dependencies\{d992c12e-cab2-426f-bde3-fb8c53950b0d}")) {
            Write-ADTLogEntry -Message "Visual C++ 2015 x64 not detected. Installing."
            Start-ADTProcess -FilePath "$($adtSession.DirSupportFiles)\Visual C++ 2015\vc_redist.x64.exe" -ArgumentList "/q /norestart" -IgnoreExitCodes "1638" -ErrorAction SilentlyContinue
        }
        }
        # Raw PowerShell: Control flow block preserved as-is
        If (-not (Test-Path -Path "HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Dependencies\{e2803110-78b3-4664-a479-3611a381656a}")) {
        Write-ADTLogEntry -Message "Visual C++ 2015 x86 not detected. Installing."
        Start-ADTProcess -FilePath "$($adtSession.DirSupportFiles)\Visual C++ 2015\vc_redist.x86.exe" -ArgumentList "/q /norestart" -IgnoreExitCodes "1638" -ErrorAction SilentlyContinue
        }
        # Raw PowerShell: Control flow block preserved as-is
        If ($Is64Bit) {
        If (-not (Test-Path -Path "HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Products\3367A02690A78A24580870A644384C0B")) {
            Write-ADTLogEntry -Message "Visual C++ 2019 x64 not detected. Installing."
            Start-ADTProcess -FilePath "$($adtSession.DirSupportFiles)\Visual C++ 2019\VC_redist.x64.exe" -ArgumentList "/q /norestart" -IgnoreExitCodes "1638" -ErrorAction SilentlyContinue
        }
        }
        # Raw PowerShell: Control flow block preserved as-is
        If (-not (Test-Path -Path "HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Products\01DCD275E2FC1D341815B89DCA09680D")) {
        Write-ADTLogEntry -Message "Visual C++ 2019 x86 not detected. Installing."
        Start-ADTProcess -FilePath "$($adtSession.DirSupportFiles)\Visual C++ 2019\VC_redist.x86.exe" -ArgumentList "/q /norestart" -IgnoreExitCodes "1638" -ErrorAction SilentlyContinue
        }
        # Raw PowerShell: PowerShell script block
        ## Install .NET Framework 4.6.2
        $DotNetVersion = "394806"
        $DotNetInstall = "$($adtSession.DirSupportFiles)\.NET Framework 4.6.2\NDP462-KB3151800-x86-x64-AllOS-ENU.exe"
        $DotNetParams = "/q /norestart"
        # Raw PowerShell: Control flow block preserved as-is
        If ((Get-ADTRegistryKey "HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full" -Name "Release") -lt $DotNetVersion) {
        $thumbPrint = "‎8f43288ad272f3103b6fb1428485ea3014c0bcfe"
        If (-not(Test-Path -Path "Cert:\LocalMachine\Root\$thumbPrint")) {
            Write-ADTLogEntry -Message "Importing MicrosoftRootCertificateAuthority2011.cer for .NET Framework $DotNetVersion"
            Start-ADTProcess -FilePath "certutil" -ArgumentList "-addstore `"Root`" `"$($adtSession.DirSupportFiles)\.NET Framework 4.6.2\MicrosoftRootCertificateAuthority2011.cer`""
        }

        Write-ADTLogEntry -Source $deployAppScriptFriendlyName -Message ".NET version is < [string]$DotNetVersion, installing"
        Start-ADTProcess -FilePath "$DotNetInstall" -ArgumentList "$DotNetParams" -WaitForMSIExec:$true
        }
        # Raw PowerShell: PowerShell script block
        ## Install Certificate
        $DomainNameCheck = (Get-WmiObject -Class Win32_ComputerSystem).Domain
        # Raw PowerShell: Control flow block preserved as-is
        If (-NOT ($DomainNameCheck -eq "1dc.com")) {
        ##Start-ADTProcess -FilePath "certutil.exe" -ArgumentList "-p `"Verintprod1!`" -importPFX `"$($adtSession.DirSupportFiles)\impact360.1dc.com.pfx`""
        ##Start-ADTProcess -FilePath "certutil.exe" -ArgumentList "-f -p `"Verintprod1!`" -importPFX root `"$($adtSession.DirSupportFiles)\impact360.1dc.com.pfx`""

        function Import-PfxCertificate {
            param([String]$certPath,[String]$certRootStore = “LocalMachine”,[String]$certStore = “Root”,$pfxPass = "Verintprod1!")
            $pfx = new-object System.Security.Cryptography.X509Certificates.X509Certificate2
            if ($pfxPass -eq $null) {$pfxPass = read-host “Enter the pfx password” -assecurestring}
            $pfx.import($certPath,$pfxPass,“Exportable,PersistKeySet”)
            $store = new-object System.Security.Cryptography.X509Certificates.X509Store($certStore,$certRootStore)
            $store.open(“MaxAllowed”)
            $store.add($pfx)
            $store.close()
        }

        Import-PfxCertificate -certpath "$($adtSession.DirSupportFiles)\impact360.1dc.com.pfx"

        Start-ADTProcess -FilePath "certutil.exe" -ArgumentList "-f -addstore -enterprise root `"$($adtSession.DirSupportFiles)\FDC_InternalMediumAssurance.cer`""
        Start-ADTProcess -FilePath "certutil.exe" -ArgumentList "-f -addstore -enterprise root `"$($adtSession.DirSupportFiles)\FDC_MediumAssurance.cer`""

        }
        # <SPA:CustomCode Phase="Pre-Install" Guide="Perform Pre-Installation tasks here">
        # TODO: Perform Pre-Installation tasks here
        # </SPA:CustomCode>

    ##================================================
    ## MARK: Install
    ##================================================
    $adtSession.InstallPhase = $adtSession.DeploymentType

    ## Handle Zero-Config MSI installations.
    if ($adtSession.UseDefaultMsi)
    {
        $ExecuteDefaultMSISplat = @{ Action = $adtSession.DeploymentType; FilePath = $adtSession.DefaultMsiFile }
        if ($adtSession.DefaultMstFile)
        {
            $ExecuteDefaultMSISplat.Add('Transforms', $adtSession.DefaultMstFile)
        }
        Start-ADTMsiProcess @ExecuteDefaultMSISplat
        if ($adtSession.DefaultMspFiles)
        {
            $adtSession.DefaultMspFiles | Start-ADTMsiProcess -Action Patch
        }
    }

        Start-ADTMsiProcess -Action 'Install' -FilePath "$($adtSession.DirFiles)\Desktop Resources\KB213008-Verint-15.2.9.166.msi" -ArgumentList 'USE_COMMAND_LINE=1 ALLUSERS=1 MSIRESTARTMANAGER=1 MSIRESTARTMANAGERCONTROL=Disable MSIRMSHUTDOWN=2 ROOTDRIVE=C:\ MSIDISABLERMRESTART=Disable REBOOT=ReallySuppress /qn /norestart' -ErrorAction Stop
        Start-ADTMsiProcess -Action 'Install' -FilePath "$($adtSession.DirFiles)\Screen Capture Module\KB212451-15.2.9.563.msi" -ArgumentList 'ENCRYPTION_DATAENCRYPT=FALSE FQDN=TRUE SENDFQDN=1 CONN_INTG_SVC=TRUE INTG_SERVERS=W1PVAP2376.1dc.com:29522,W3PVAP1869.1dc.com:29522,W1PVAP2377.1dc.com:29522,W3PVAP1870.1dc.com:29522 ALLUSERS=1 MSIRESTARTMANAGER=1 MSIRESTARTMANAGERCONTROL=Disable MSIRMSHUTDOWN=2 ROOTDRIVE=C:\ MSIDISABLERMRESTART=Disable REBOOT=ReallySuppress /qn /norestart' -ErrorAction Stop
        Start-ADTMsiProcess -Action 'Install' -FilePath "$($adtSession.DirFiles)\PlayBack\KB211676-15.2.0.1676.msi" -ArgumentList 'PLAYBACK_ENCRYPTED=1 PLAYBACK_ENCRYPTIONWEBSERVICE=verintprod.1dc.com ARPNOMODIFY=1 ALLUSERS=1 MSIRESTARTMANAGER=1 MSIRESTARTMANAGERCONTROL=Disable MSIRMSHUTDOWN=2 ROOTDRIVE=C:\ MSIDISABLERMRESTART=Disable REBOOT=ReallySuppress /qn /norestart' -ErrorAction Stop
        Start-ADTMsiProcess -Action 'Install' -FilePath "$($adtSession.DirFiles)\DPA Client\KB222637-64-15.2.9.254.msi" -ArgumentList 'CONFIGSERVER=verintprod.1dc.com USEHTTPS=Y AUTOSTART=Y ALLUSERS=1 MSIRESTARTMANAGER=1 MSIRESTARTMANAGERCONTROL=Disable MSIRMSHUTDOWN=2 ROOTDRIVE=C:\ MSIDISABLERMRESTART=Disable REBOOT=ReallySuppress /qn /norestart'
        # Raw PowerShell: Control flow block preserved as-is
        If (Test-Path -Path "HKLM:Software\Mozilla\Mozilla Firefox") {
            $ProfilePaths = Get-ADTUserProfiles | Select-Object -ExpandProperty 'ProfilePath'
            ForEach ($Profile in $ProfilePaths) {
                If (-not(Test-Path -Path "$Profile\AppData\Roaming\Mozilla\Extensions\{ec8030f7-c20a-464f-9b0e-13a3a9e97384}")) {
                    New-ADTFolder -Path "$Profile\AppData\Roaming\Mozilla\Extensions\{ec8030f7-c20a-464f-9b0e-13a3a9e97384}"
                }
                Copy-ADTFile -Path "$($adtSession.DirSupportFiles)\Firefox\dpa-client-ff-15.2.6.2@verint.com.xpi" -Destination "$Profile\AppData\Roaming\Mozilla\Extensions\{ec8030f7-c20a-464f-9b0e-13a3a9e97384}\dpa-client-ff-15.2.6.2@verint.com.xpi"
            }
        }
        Else {
            Write-ADTLogEntry -Message "Firefox not detected, skipping DPA Firefox extensions."
        }
        Start-ADTMsiProcess -Action 'Install' -FilePath "$($adtSession.DirFiles)\Desktop Connection Manager\KB221897-15.2.9.178.msi" -ArgumentList 'SERVERADDR=verintprod.1dc.com USEHTTPS=Y USEFQDN=Y ALLUSERS=1 MSIRESTARTMANAGER=1 MSIRESTARTMANAGERCONTROL=Disable MSIRMSHUTDOWN=2 ROOTDRIVE=C:\ MSIDISABLERMRESTART=Disable REBOOT=ReallySuppress /qn /norestart' -ErrorAction Stop
        Start-ADTMsiProcess -Action 'Install' -FilePath "$($adtSession.DirFiles)\Desktop Messaging Client\KB221898-15.2.9.178.msi" -ArgumentList 'AUTOSTART=Y ALLUSERS=1 MSIRESTARTMANAGER=1 MSIRESTARTMANAGERCONTROL=Disable MSIRMSHUTDOWN=2 ROOTDRIVE=C:\ MSIDISABLERMRESTART=Disable REBOOT=ReallySuppress /qn /norestart' -ErrorAction Stop
        Start-ADTMsiProcess -Action 'Install' -FilePath "$($adtSession.DirFiles)\Logger\KB211074-15.2.9.157.msi" -ArgumentList 'USE_COMMAND_LINE=1 ALLUSERS=1 ARPNOMODIFY=1 MSIRESTARTMANAGER=1 MSIRESTARTMANAGERCONTROL=Disable MSIRMSHUTDOWN=2 ROOTDRIVE=C:\ MSIDISABLERMRESTART=Disable REBOOT=ReallySuppress /qn /norestart' -ErrorAction Stop
        # <SPA:CustomCode Phase="Install" Guide="Perform Installation tasks here">
        # TODO: Perform Installation tasks here
        # </SPA:CustomCode>

    ##================================================
    ## MARK: Post-Install
    ##================================================
    $adtSession.InstallPhase = "Post-$($adtSession.DeploymentType)"

        Remove-ADTRegistryKey -LiteralPath 'HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{5256667C-27D7-4767-85B3-89153FEF5026}' -Name 'URLInfoAbout'
        Remove-ADTRegistryKey -LiteralPath 'HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{5256667C-27D7-4767-85B3-89153FEF5026}' -Name 'URLUpdateInfo'
        Remove-ADTRegistryKey -LiteralPath 'HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{5256667C-27D7-4767-85B3-89153FEF5026}' -Name 'HelpLink'
        # Raw PowerShell: PowerShell script block
        #Create Dummy Registry

         $sName = "Verient_DesktopClientTools_15.2.9"
         $sDummyRegistry = "HKLM:\SOFTWARE\Fiserv\Applications\$sName"
        [hashtable]$sRegkeyName = @{'Application Name'="$adtSession.AppName";'InstallDate'="$value";'Manufacturer'="$adtSession.AppVendor";'Version'="$adtSession.AppVersion"}
        # Raw PowerShell: Control flow block preserved as-is
        foreach ($sRegkeyNames in $sRegkeyName.GetEnumerator()) {
        $sRegType = 'String'
        Try {
        Set-ADTRegistryKey -LiteralPath $sDummyRegistry -Name $sRegkeyNames.Name -Value $sRegkeyNames.Value -Type $sRegType -ErrorAction 'stop'
        Write-ADTLogEntry -Message "Successfully created $($sDummyRegistry)"
        }
        Catch {
        Write-ADTLogEntry -Message "Failed to create $($sDummyRegistry)"
        }
        }
        # <SPA:CustomCode Phase="Post-Install" Guide="Perform Post-Installation tasks here">
        # TODO: Perform Post-Installation tasks here
        # </SPA:CustomCode>
}

function Uninstall-ADTDeployment
{
    [CmdletBinding()]
    param
    (
    )

    ##================================================
    ## MARK: Pre-Uninstall
    ##================================================
    $adtSession.InstallPhase = "Pre-$($adtSession.DeploymentType)"

        ## Show Welcome Message, close processes if specified, verify disk space, persist the prompt.
        $saiwParams = @{
            CheckDiskSpace = $true
            PersistPrompt = $true
        }
        if ($adtSession.AppProcessesToClose.Count -gt 0)
        {
            $saiwParams.Add('CloseProcesses', $adtSession.AppProcessesToClose)
        }
        Show-ADTInstallationWelcome @saiwParams
        ## Show Progress Message (with the default message).
        Show-ADTInstallationProgress -WindowLocation 'TopCenter'
        # Raw PowerShell: Control flow block preserved as-is
        If (Test-ADTServiceExists -Name "DCUBrowserService") {
        Stop-ADTServiceAndDependencies -Name "DCUBrowserService"
        }
        # Raw PowerShell: Control flow block preserved as-is
        If (Get-Process -Name 'DCUapp' -ErrorAction SilentlyContinue) {
        Start-ADTProcess -FilePath "TASKKILL" -ArgumentList "/F /IM DCUapp.exe /t" -WindowStyle Hidden
        Start-Sleep -Seconds 5
        }
        # Raw PowerShell: Control flow block preserved as-is
        If (Get-Process -Name 'DPAWow64' -ErrorAction SilentlyContinue) {
        Start-ADTProcess -FilePath "TASKKILL" -ArgumentList "/F /IM DPAWow64.exe /t" -WindowStyle Hidden
        Start-Sleep -Seconds 5
        }
        # Raw PowerShell: Control flow block preserved as-is
        If (Get-Process -Name 'svstr' -ErrorAction SilentlyContinue) {
        Start-ADTProcess -FilePath "TASKKILL" -ArgumentList "/F /IM svstr.exe /t" -WindowStyle Hidden
        Start-Sleep -Seconds 5
        }
        # Raw PowerShell: Control flow block preserved as-is
        If (Get-Process -Name 'DPAMessageClient' -ErrorAction SilentlyContinue) {
        Start-ADTProcess -FilePath "TASKKILL" -ArgumentList "/F /IM DPAMessageClient.exe /t" -WindowStyle Hidden
        Start-Sleep -Seconds 5
        }
        # Raw PowerShell: Control flow block preserved as-is
        If (Get-Process -Name 'CaptureService' -ErrorAction SilentlyContinue) {
        Start-ADTProcess -FilePath "TASKKILL" -ArgumentList "/F /IM CaptureService.exe /t" -WindowStyle Hidden
        Start-Sleep -Seconds 5
        }
        # <SPA:CustomCode Phase="Pre-Uninstall" Guide="Perform Pre-Uninstallation tasks here">
        # TODO: Perform Pre-Uninstallation tasks here
        # </SPA:CustomCode>

    ##================================================
    ## MARK: Uninstall
    ##================================================
    $adtSession.InstallPhase = $adtSession.DeploymentType

    ## Handle Zero-Config MSI uninstallations.
    if ($adtSession.UseDefaultMsi)
    {
        $ExecuteDefaultMSISplat = @{ Action = $adtSession.DeploymentType; FilePath = $adtSession.DefaultMsiFile }
        if ($adtSession.DefaultMstFile)
        {
            $ExecuteDefaultMSISplat.Add('Transforms', $adtSession.DefaultMstFile)
        }
        Start-ADTMsiProcess @ExecuteDefaultMSISplat
    }

        # Raw PowerShell: PowerShell script block
        # <Perform Uninstallation tasks here>


        ## Uninstall All Screen Capture Module Versions
        $ScreenCapture = Get-ADTApplication -Name 'Screen Capture Module' -NameMatch 'Exact'
        # Raw PowerShell: Control flow block preserved as-is
        If($ScreenCapture) {
            Write-ADTLogEntry -Message "Attempting to Removing Screen Capture Module."
        "{4F6241BF-B9B8-4439-8185-1D8FA52C1061}", <# 15.2.8.747 #>`
            "{BF4A5C34-57F2-4727-A1EB-359BD4BFEA8F}", <# 15.2.7.600 #>`
            "{8585ED5A-B7B3-4D27-85CF-105FD1E617F3}", <# 15.2.5.377 #>`
            "{AF86FAB8-F969-49C2-B0BD-0948E625248B}", <# 15.2 #>`
            "{E473C64C-48DF-4205-AE89-1093ABF80BEE}", <# 15.1 #>`
            "{ACF6A782-283F-474D-8EA4-F4A0D91A3B81}", <# 11 #>`
            "{F894CFF6-1501-43C1-8C51-69E769C4CD21}", <#  #>`
            "{3F69F2D9-FCB0-44F6-B4B9-61A82FD5A408}", <#  #>`
            "{DA905477-8428-49B7-A8F2-EC029CBAC023}", <#15.2.9#>`
             "{5256667C-27D7-4767-85B3-89153FEF5026}" <#15.2.9#>`
             | ForEach-Object { Start-ADTMsiProcess -Action 'Uninstall' -FilePath "$_" } <# foreach item, uninstall #>
        }
        Uninstall-ADTApplication -Name 'Screen Capture Module' -NameMatch 'Exact' -ApplicationType 'MSI'
        # Raw PowerShell: PowerShell script block
                $RecheckScapture = Get-ADTApplication -Name 'Screen Capture Module' -NameMatch 'Exact'
        # Raw PowerShell: Control flow block preserved as-is
        If($RecheckScapture) {
            Write-ADTLogEntry -Message "Screen Capture Module Removal Failed."
        }
        Else {
            Write-ADTLogEntry -Message "Screen Capture Module Successfully Removed."
        }
        Start-ADTMsiProcess -Action 'Uninstall' -ProductCode '{5256667C-27D7-4767-85B3-89153FEF5026}' -ArgumentList '/qn '
        # Raw PowerShell: PowerShell script block
        ## Uninstall All Playback Versions
        $Playback = Get-ADTApplication -Name 'Playback' -NameMatch 'Exact'
        # Raw PowerShell: Control flow block preserved as-is
        If($Playback) {
                    "{A7013F30-90A8-41C9-B6F1-7DDE49311B11}", <# 15.2.0.316 #>`
                    "{FA98207B-3919-4A25-9CE8-80ADD7BAB7A7}", <# 15.2,0,300 #>`
                    "{22B23068-FAAA-48EE-85F5-419C091C6333}", <# 15.2 #>`
                    "{9717AA1A-3A0F-4488-A468-E5F6727FDAD2}", <# 15.1 #>`
                    "{FEE25469-462E-4850-9C75-35D6BA91BC2C}", <# 11 #>`
                    "{0F274A85-8973-4324-A1AB-3C32D39B9BA1}", <#  #>`
                    "{6A140312-6A6F-434F-832D-A786F597989C}", <# #>`
                    "{97024FA6-544F-4159-9067-C0AF13AC0F89}", <# #>`
                    "{6ED181DA-F036-4734-A41D-1BEF909020F7}", <#  #>`
                    "{7DB74931-8DDE-4F0D-8929-5E8294B79845}", <# #>`
                    "{89EA4623-E4A6-4B10-A8C7-0C1FD8CE2EC1}", <# #>`
                    "{41835F9D-59DD-4529-B7F0-542CC42B0B28}" <#15.2.9 #>`
        | ForEach-Object { Start-ADTMsiProcess -Action 'Uninstall' -FilePath "$_" } <# foreach item, uninstall #>
                }
        Uninstall-ADTApplication -Name 'Playback' -NameMatch 'Exact' -ApplicationType 'MSI'
        # Raw PowerShell: PowerShell script block
                $RecheckPlayback = Get-ADTApplication -Name 'Playback' -NameMatch 'Exact'
        # Raw PowerShell: Control flow block preserved as-is
        If($RecheckPlayback) {
            Write-ADTLogEntry -Message "Playback Removal Failed."
        }
        Else {
            Write-ADTLogEntry -Message "Playback Successfully Removed."
        }
        # Raw PowerShell: PowerShell script block
        ## Uninstall All DPA Client Versions
        $DPAClient = Get-ADTApplication -Name 'Desktop & Process Analytics Client*' -NameMatch 'Wildcard'
        # Raw PowerShell: Control flow block preserved as-is
        If($DPAClient) {
        "{5EA14529-9A8B-4EC4-B19E-E343468CFBA5}", <# DPA x64 15.2.8.118 #>`
        "{8BA86C5A-6042-46E0-A1B8-0C9F79E56AA2}", <# DPA x32 15.2.8.118 #>`
            "{AF2463AC-FD42-41FC-99F6-BB27CB101E12}", <# DPA x64 15.2.7.124 #>`
            "{A582BE0B-B5FB-43A6-AE21-99FCBF6C2072}", <# DPA x32 15.2.7.124 #>`
            "{BC0DB85B-747E-4AB3-9C63-741BD660555B}", <# DPA x64 15.2.5 #>`
            "{0CD4B184-A8B9-4526-B128-2CD6E7DB1970}", <# DPA x32 15.2.5 #>`
            "{CBD809D8-724F-4F63-93BC-FD674F4ED711}", <# DPA x64 15.2.2.153 Process Discovery Plugin #>`
            "{CED814F5-781C-42C3-A621-162698063695}", <# 15.1 #>`
            "{5B87EDB6-6B7A-4AE7-BECF-23A3F4F7DF9B}",`
            "{A9ABACAE-393B-4A7B-A09A-616A19D54C6C}",<# DPA x64 15.2.2.153 #>`
            "{AF694898-4B4B-46E5-A2AA-8AE4B43E4A04}",<# DPA x64 15.2.9 #>`
            "{8DEF13F1-0A13-4116-8F45-43F84FCA955D}"<# DPA x64 15.2.9 #>`
                | ForEach-Object { Start-ADTMsiProcess -Action 'Uninstall' -FilePath "$_" } <# foreach item, uninstall #>
        }
        Uninstall-ADTApplication -Name 'Desktop & Process Analytics Client*' -NameMatch 'Wildcard' -ApplicationType 'MSI'
        # Raw PowerShell: PowerShell script block
                $RecheckDPAClient = Get-ADTApplication -Name 'Desktop & Process Analytics Client*' -NameMatch 'Wildcard'
        # Raw PowerShell: Control flow block preserved as-is
        If($RecheckDPAClient) {
            Write-ADTLogEntry -Message "DPA Client Removal Failed."
        }
        Else {
            Write-ADTLogEntry -Message "DPA Client Successfully Removed."
        }
        # Raw PowerShell: PowerShell script block
        ## Uninstall All Desktop Connection Manager Versions
        $DCManager = Get-ADTApplication -Name 'Desktop Messaging Connection Manager*' -NameMatch 'Wildcard'
        # Raw PowerShell: Control flow block preserved as-is
        If($DCManager) {
        "{21840FE9-B0B9-4282-9216-1ACE39764678}", <# 15.2.8.15 #>`
            "{FDFF1354-F27B-477E-BEE0-CB1407E5E6C2}", <# 15.2.7.14 #>`
            "{BD4B93DB-EFD0-4A09-997D-71543A0BE200}", <# 15.2.5 #>`
            "{8310EF63-CEB3-418A-9F49-7CE4E377F04D}", <# 15.2 #>`
            "{C9529B20-AF44-485B-8990-3C07A82D9B2E}", <# 15.1 #>`
            "{0366602F-6C92-4354-BC7C-994AD974F308}" <# 15.2.9 #>`
              | ForEach-Object { Start-ADTMsiProcess -Action 'Uninstall' -FilePath "$_" } <# foreach item, uninstall #>
        }
        Uninstall-ADTApplication -Name 'Desktop Messaging Connection Manager*' -NameMatch 'Wildcard' -ApplicationType 'MSI'
        # Raw PowerShell: PowerShell script block
                $RecheckDCManager = Get-ADTApplication -Name 'Desktop Messaging Connection Manager*' -NameMatch 'Wildcard'
        # Raw PowerShell: Control flow block preserved as-is
        If($RecheckDCManager) {
            Write-ADTLogEntry -Message "Desktop Messaging Connection Manager Removal Failed."
        }
        Else {
            Write-ADTLogEntry -Message "Desktop Messaging Connection Manager Successfully Removed."
        }
        # Raw PowerShell: PowerShell script block
        ## Uninstall All Desktop Messaging Client Versions
        $DMClient = Get-ADTApplication -Name 'Desktop Messaging Client*' -NameMatch 'Wildcard'
        # Raw PowerShell: Control flow block preserved as-is
        If($DMClient) {
        "{44010D16-5431-4E4E-B596-725B68EA80FA}", <# 15.2.8.10 #>`
            "{09CD1FAA-BED3-4731-9398-6F422DBB122F}", <# 15.2.7.14 #>`
            "{9D7BD7C0-28F4-4509-A5CE-E215EC775ADA}", <# 15.2.5 #>`
            "{FD7A4C10-ED8E-40F2-9B49-1867D5962152}", <# 15.2 #>`
            "{009A24B5-2EEF-44D5-98D5-F710FD7D7BA9}", <#  #>`
            "{FC770B3D-FA18-44A0-938F-4B6D1260F7D0}", <# 15.1 #>`
            "{0471B603-5C8F-47D2-A8B6-2AFEB611C3BC}" <# 15.2.9 #>`
              | ForEach-Object { Start-ADTMsiProcess -Action 'Uninstall' -FilePath "$_" } <# foreach item, uninstall #>
        }
        Uninstall-ADTApplication -Name 'Desktop Messaging Client*' -NameMatch 'Wildcard' -ApplicationType 'MSI'
        # Raw PowerShell: PowerShell script block
                $RecheckDMClient = Get-ADTApplication -Name 'Desktop Messaging Client*' -NameMatch 'Wildcard'
        # Raw PowerShell: Control flow block preserved as-is
        If($RecheckDMClient) {
            Write-ADTLogEntry -Message "Desktop Messaging Client Removal Failed."
        }
        Else {
            Write-ADTLogEntry -Message "Desktop Messaging Client Successfully Removed."
        }
        # Raw PowerShell: PowerShell script block
        ## Uninstall All Verint Logger Versions
        $VLogger = Get-ADTApplication -Name 'Logger' -NameMatch 'Exact'
        # Raw PowerShell: Control flow block preserved as-is
        If($VLogger) {
        "{2A55E493-F199-4888-807A-9DA554A92DED}", <# 15.2.4.74 #>`
        "{5BC0BD43-6B95-43CF-960D-D30670370E2C}", <# 15.1 #>`
        "{72607611-A697-4C71-9FC9-9C52082CB951}" <# 15.1 #>`
           | ForEach-Object { Start-ADTMsiProcess -Action 'Uninstall' -FilePath "$_" } <# foreach item, uninstall #>
        }
        Uninstall-ADTApplication -Name 'Logger' -NameMatch 'Exact' -ApplicationType 'MSI'
        # Raw PowerShell: PowerShell script block
                $RecheckVLogger = Get-ADTApplication -Name 'Logger' -NameMatch 'Exact'
        # Raw PowerShell: Control flow block preserved as-is
        If($RecheckVLogger) {
            Write-ADTLogEntry -Message "Verint Logger Removal Failed."
        }
        Else {
            Write-ADTLogEntry -Message "Verint Logger Successfully Removed."
        }
        # Raw PowerShell: PowerShell script block
        ## Uninstall All Desktop Resources Versions
        $DResources = Get-ADTApplication -Name 'Desktop Resources Verint' -NameMatch 'Exact'
        # Raw PowerShell: Control flow block preserved as-is
        If($DResources) {
        "{2897355D-DFC1-423F-8734-26AB9A6F2483}", <# 15.2.8.14 #>`
            "{51801F63-2D4C-45FD-8CD0-D2F7385D08A8}", <# 15.2.7.15 #>`
            "{E353C20E-5F8D-47C8-81ED-54BC60585B93}", <# 15.2 #>`
            "{9FAE0F49-CBFE-47A7-8C50-767A4273996B}", <# 15.1 #>`
            "{27538D70-AE44-4CF0-ABFB-2A465C930F35}", <# 11.0 #>`
            "{C30A6C7B-2DFA-4389-820D-2D1307B866F7}" <# 15.2.9 #>`
              | ForEach-Object { Start-ADTMsiProcess -Action 'Uninstall' -FilePath "$_" } <# foreach item, uninstall #>
        }
        Uninstall-ADTApplication -Name 'Desktop Resources Verint' -NameMatch 'Exact' -ApplicationType 'MSI'
        # Raw PowerShell: PowerShell script block
                $RecheckDResources = Get-ADTApplication -Name 'Desktop Resources Verint' -NameMatch 'Exact'
        # Raw PowerShell: Control flow block preserved as-is
        If($RecheckDResources) {
            Write-ADTLogEntry -Message "Desktop Resources Verint Removal Failed."
        }
        Else {
            Write-ADTLogEntry -Message "Desktop Resources Verint Successfully Removed."
        }
        Start-ADTMsiProcess -Action 'Uninstall' -ProductCode '{5256667C-27D7-4767-85B3-89153FEF5026}' -ArgumentList '/qn /norestart'
        # <SPA:CustomCode Phase="Uninstall" Guide="Perform Uninstallation tasks here">
        # TODO: Perform Uninstallation tasks here
        # </SPA:CustomCode>

    ##================================================
    ## MARK: Post-Uninstall
    ##================================================
    $adtSession.InstallPhase = "Post-$($adtSession.DeploymentType)"

        # Raw PowerShell: PowerShell script block
         ## <Perform Post-Uninstallation tasks here>

        Remove-Item -Path "HKLM:\SOFTWARE\Fiserv\Applications\Verient_DesktopClientTools_15.2.9" -Force -Recurse -ErrorAction 'stop'
        # Raw PowerShell: Control flow block preserved as-is
        if((test-path -path "C:\Program Files\Verint")){
        Write-ADTLogEntry -Message "C:\Program Files\Verint folder still exists so removing."
        Remove-ADTFolder -path "C:\Program Files\Verint" -ErrorAction SilentlyContinue
        }
        # Raw PowerShell: Control flow block preserved as-is
        if((test-path -path "C:\Program Files (x86)\Verint")){
        Write-ADTLogEntry -Message "C:\Program Files (x86)\Verint folder still exists so removing."
        Remove-ADTFolder -path "C:\Program Files (x86)\Verint" -ErrorAction SilentlyContinue
        }
        # Raw PowerShell: Control flow block preserved as-is
        if((test-path -path "C:\ProgramData\Verint")){
        Write-ADTLogEntry -Message "C:\ProgramData\Verint folder still exists so removing."
        Remove-ADTFolder -path "C:\ProgramData\Verint" -ErrorAction SilentlyContinue
        }
        # <SPA:CustomCode Phase="Post-Uninstall" Guide="Perform Post-Uninstallation tasks here">
        # TODO: Perform Post-Uninstallation tasks here
        # </SPA:CustomCode>
}


##================================================
## MARK: Initialization
##================================================

$ErrorActionPreference = [System.Management.Automation.ActionPreference]::Stop
$ProgressPreference = [System.Management.Automation.ActionPreference]::SilentlyContinue
Set-StrictMode -Version 1

try
{
    if (Test-Path -LiteralPath "$PSScriptRoot\PSAppDeployToolkit\PSAppDeployToolkit.psd1" -PathType Leaf)
    {
        Get-ChildItem -LiteralPath "$PSScriptRoot\PSAppDeployToolkit" -Recurse -File | Unblock-File -ErrorAction Ignore
        Import-Module -FullyQualifiedName @{ ModuleName = "$PSScriptRoot\PSAppDeployToolkit\PSAppDeployToolkit.psd1"; Guid = '8c3c366b-8606-4576-9f2d-4051144f7ca2'; ModuleVersion = '4.1.8' } -Force
    }
    else
    {
        Import-Module -FullyQualifiedName @{ ModuleName = 'PSAppDeployToolkit'; Guid = '8c3c366b-8606-4576-9f2d-4051144f7ca2'; ModuleVersion = '4.1.8' } -Force
    }

    $iadtParams = Get-ADTBoundParametersAndDefaultValues -Invocation $MyInvocation
    $adtSession = Remove-ADTHashtableNullOrEmptyValues -Hashtable $adtSession
    $adtSession = Open-ADTSession @adtSession @iadtParams -PassThru
}
catch
{
    $Host.UI.WriteErrorLine((Out-String -InputObject $_ -Width ([System.Int32]::MaxValue)))
    exit 60008
}


##================================================
## MARK: Invocation
##================================================

try
{
    Get-ChildItem -LiteralPath $PSScriptRoot -Directory | & {
        process
        {
            if ($_.Name -match 'PSAppDeployToolkit\..+$')
            {
                Get-ChildItem -LiteralPath $_.FullName -Recurse -File | Unblock-File -ErrorAction Ignore
                Import-Module -Name $_.FullName -Force
            }
        }
    }

    & "$($adtSession.DeploymentType)-ADTDeployment"
    Close-ADTSession
}
catch
{
    $mainErrorMessage = "An unhandled error within [$($MyInvocation.MyCommand.Name)] has occurred.`n$(Resolve-ADTErrorRecord -ErrorRecord $_)"
    Write-ADTLogEntry -Message $mainErrorMessage -Severity 3
    Close-ADTSession -ExitCode 60001
}
