<#
.SYNOPSIS
    Tanium Client 7.8.2.1149 - PSADT v4 deployment script.
    Generated by SPA Workbench on 2026-06-03.

.DESCRIPTION
    Performs Install, Uninstall, or Repair of Tanium Client 7.8.2.1149.
    Uses the PSAppDeployToolkit v4 function-based architecture.

.NOTES
    Framework : PSAppDeployToolkit 4.1.0
    Package   : tanium-client-7821149
    Version   : 7.8.2.1149
#>

[CmdletBinding()]
param
(
    [Parameter(Mandatory = $false)]
    [ValidateSet('Install', 'Uninstall', 'Repair')]
    [System.String]$DeploymentType,

    [Parameter(Mandatory = $false)]
    [ValidateSet('Auto', 'Interactive', 'NonInteractive', 'Silent')]
    [System.String]$DeployMode,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$SuppressRebootPassThru,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$TerminalServerMode,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$DisableLogging
)


##================================================
## MARK: Variables
##================================================

$adtSession = @{
    AppVendor              = 'Tanium Inc.'
    AppName                = 'Tanium Client 7.8.2.1149'
    AppVersion             = '7.8.2.1149'
    AppArch                = 'x64'
    AppLang                = 'EN'
    AppRevision            = '01'
    AppSuccessExitCodes    = @(0)
    AppRebootExitCodes     = @(1641, 3010)
    AppProcessesToClose    = @()
    AppScriptVersion       = '1.0.0'
    AppScriptDate          = '06-03-2026'
    AppScriptAuthor        = 'Gouthami'
    RequireAdmin           = $true

    InstallName            = 'TaniumInc_TaniumClient_7.8.2.1149'
    InstallTitle           = 'TaniumInc_TaniumClient_7.8.2.1149'

    DeployAppScriptFriendlyName = $MyInvocation.MyCommand.Name
    DeployAppScriptParameters   = $PSBoundParameters
    DeployAppScriptVersion      = '4.1.0'
}


##================================================
## MARK: Deployment Flow
##================================================

function Install-ADTDeployment
{

    [CmdletBinding()]
    param
    (
    )

    ##================================================
    ## MARK: Pre-Install
    ##================================================
    $adtSession.InstallPhase = "Pre-$($adtSession.DeploymentType)"

        # Raw PowerShell: Legacy or custom script block
        Show-ADTInstallationProgress -StatusMessage 'Installation in Progress...' -WindowLocation 'TopCenter'
        # Raw PowerShell: Control flow block preserved as-is
        If (Test-Path -Path "$envProgramFilesx86\Tanium\Tanium Client\uninst.exe"){
            Start-ADTProcess -FilePath "$envProgramFilesx86\Tanium\Tanium Client\uninst.exe" -ArgumentList '/S'
            }
        # Raw PowerShell: Control flow block preserved as-is
        If(Test-Path -Path "$envProgramFiles\Tanium\Tanium Client\uninst.exe") {
            Start-ADTProcess -FilePath "$envProgramFiles\Tanium\Tanium Client\uninst.exe" -ArgumentList '/S'
            }
        Start-Sleep -Seconds 10
        # <SPA:CustomCode Phase="Pre-Install" Guide="Enter custom pre-installation script code here (e.g. show welcome prompt, stop processes, check requirements)">
        # TODO: Enter custom pre-installation script code here (e.g. show welcome prompt, stop processes, check requirements)
        # </SPA:CustomCode>

    ##================================================
    ## MARK: Install
    ##================================================
    $adtSession.InstallPhase = $adtSession.DeploymentType

        # Raw PowerShell: Control flow block preserved as-is
        if ($adtSession.UseDefaultMsi)
            {
                $ExecuteDefaultMSISplat = @{ Action = $adtSession.DeploymentType; FilePath = $adtSession.DefaultMsiFile }
                if ($adtSession.DefaultMstFile)
                {
                    $ExecuteDefaultMSISplat.Add('Transform', $adtSession.DefaultMstFile)
                }
                Start-ADTMsiProcess @ExecuteDefaultMSISplat
                if ($adtSession.DefaultMspFiles)
                {
                    $adtSession.DefaultMspFiles | Start-ADTMsiProcess -Action Patch
                }
            }
        Start-ADTProcess -FilePath '$($adtSession.DirFiles)\SetupClient.exe' -ArgumentList '/S' -ErrorAction Stop
        # <SPA:CustomCode Phase="Install" Guide="Enter custom installation script code here (e.g. run MSI/EXE installer, perform file copy)">
        # TODO: Enter custom installation script code here (e.g. run MSI/EXE installer, perform file copy)
        # </SPA:CustomCode>

    ##================================================
    ## MARK: Post-Install
    ##================================================
    $adtSession.InstallPhase = "Post-$($adtSession.DeploymentType)"

        # Raw PowerShell: PowerShell script block
            ##================================================
        
            ## <Perform Post-Installation tasks here>
        
            #Update Uninstall Key
        
             $InstallDate = Get-Date -Format 'yyyyMMdd'
             $InstallSource = Get-Location
        # Raw PowerShell: Control flow block preserved as-is
        If (Test-Path -Path "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Tanium Client") {
             Set-ADTRegistryKey -Key "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Tanium Client" -Name "InstallDate" -Value $InstallDate -Type String
             }
        # Raw PowerShell: Control flow block preserved as-is
        If (Test-Path -Path "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Tanium Client") {
             Set-ADTRegistryKey -Key "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Tanium Client" -Name "InstallSource" -Value $InstallSource -Type String
             }
        Start-Sleep -Seconds 10
        # Raw PowerShell: Control flow block preserved as-is
        if (!$adtSession.UseDefaultMsi)
            {
                Show-ADTInstallationPrompt -Message "$($adtSession.InstallTitle) is installed successfully from your machine." -ButtonRightText 'OK' -Icon Information -NoWait
            }
        # <SPA:CustomCode Phase="Post-Install" Guide="Enter custom post-installation script code here (e.g. apply registry keys, set environment variables, cleanup temporary files)">
        # TODO: Enter custom post-installation script code here (e.g. apply registry keys, set environment variables, cleanup temporary files)
        # </SPA:CustomCode>
}

function Uninstall-ADTDeployment
{
    [CmdletBinding()]
    param
    (
    )

    ##================================================
    ## MARK: Pre-Uninstall
    ##================================================
    $adtSession.InstallPhase = "Pre-$($adtSession.DeploymentType)"

        # Raw PowerShell: Legacy or custom script block
        Show-ADTInstallationProgress -StatusMessage 'Uninstall in Progress...' -WindowLocation 'TopCenter'
        # <SPA:CustomCode Phase="Pre-Uninstall" Guide="Enter custom pre-uninstallation script code here (e.g. show welcome prompt, close processes before uninstalling)">
        # TODO: Enter custom pre-uninstallation script code here (e.g. show welcome prompt, close processes before uninstalling)
        # </SPA:CustomCode>

    ##================================================
    ## MARK: Uninstall
    ##================================================
    $adtSession.InstallPhase = $adtSession.DeploymentType

        # Raw PowerShell: Control flow block preserved as-is
        if ($adtSession.UseDefaultMsi)
            {
                $ExecuteDefaultMSISplat = @{ Action = $adtSession.DeploymentType; FilePath = $adtSession.DefaultMsiFile }
                if ($adtSession.DefaultMstFile)
                {
                    $ExecuteDefaultMSISplat.Add('Transform', $adtSession.DefaultMstFile)
                }
                Start-ADTMsiProcess @ExecuteDefaultMSISplat
            }
        # Raw PowerShell: Control flow block preserved as-is
        If (Test-Path -Path "$envProgramFilesx86\Tanium\Tanium Client\uninst.exe"){
            Start-ADTProcess -FilePath "$envProgramFilesx86\Tanium\Tanium Client\uninst.exe" -ArgumentList '/S'
            }
        # Raw PowerShell: Control flow block preserved as-is
        If(Test-Path -Path "$envProgramFiles\Tanium\Tanium Client\uninst.exe") {
            Start-ADTProcess -FilePath "$envProgramFiles\Tanium\Tanium Client\uninst.exe" -ArgumentList '/S'
            }
        # Raw PowerShell: Control flow block preserved as-is
        If(Test-Path -path "$envProgramFilesx86\Tanium\Tanium End User Notification Tools"){
            Remove-ADTFolder -Path "$envProgramFilesx86\Tanium\Tanium End User Notification Tools"
            }
        Start-Sleep -Seconds 10
        # <SPA:CustomCode Phase="Uninstall" Guide="Enter custom uninstallation script code here (e.g. run MSI/EXE uninstall commands)">
        # TODO: Enter custom uninstallation script code here (e.g. run MSI/EXE uninstall commands)
        # </SPA:CustomCode>

    ##================================================
    ## MARK: Post-Uninstall
    ##================================================
    $adtSession.InstallPhase = "Post-$($adtSession.DeploymentType)"

        # <SPA:CustomCode Phase="Post-Uninstall" Guide="Enter custom post-uninstallation script code here (e.g. delete config folders, remove registry keys)">
        # TODO: Enter custom post-uninstallation script code here (e.g. delete config folders, remove registry keys)
        # </SPA:CustomCode>
}

function Repair-ADTDeployment
{
    [CmdletBinding()]
    param
    (
    )

    ##================================================
    ## MARK: Pre-Repair
    ##================================================
    $adtSession.InstallPhase = "Pre-$($adtSession.DeploymentType)"

        # Raw PowerShell: Legacy or custom script block
        Show-ADTInstallationProgress -StatusMessage 'Installation in Progress...' -WindowLocation 'TopCenter'
        # Raw PowerShell: Control flow block preserved as-is
        If (Test-Path -Path "$envProgramFilesx86\Tanium\Tanium Client\uninst.exe"){
            Start-ADTProcess -FilePath "$envProgramFilesx86\Tanium\Tanium Client\uninst.exe" -ArgumentList '/S'
            }
        # Raw PowerShell: Control flow block preserved as-is
        If(Test-Path -Path "$envProgramFiles\Tanium\Tanium Client\uninst.exe") {
            Start-ADTProcess -FilePath "$envProgramFiles\Tanium\Tanium Client\uninst.exe" -ArgumentList '/S'
            }
        Start-Sleep -Seconds 10
        # <SPA:CustomCode Phase="Pre-Repair" Guide="Enter custom pre-repair script code here (e.g. close processes, check corrupt states)">
        # TODO: Enter custom pre-repair script code here (e.g. close processes, check corrupt states)
        # </SPA:CustomCode>

    ##================================================
    ## MARK: Repair
    ##================================================
    $adtSession.InstallPhase = $adtSession.DeploymentType

        # Raw PowerShell: Control flow block preserved as-is
        if ($adtSession.UseDefaultMsi)
            {
                $ExecuteDefaultMSISplat = @{ Action = $adtSession.DeploymentType; FilePath = $adtSession.DefaultMsiFile }
                if ($adtSession.DefaultMstFile)
                {
                    $ExecuteDefaultMSISplat.Add('Transform', $adtSession.DefaultMstFile)
                }
                Start-ADTMsiProcess @ExecuteDefaultMSISplat
                if ($adtSession.DefaultMspFiles)
                {
                    $adtSession.DefaultMspFiles | Start-ADTMsiProcess -Action Patch
                }
            }
        Start-ADTProcess -FilePath '$($adtSession.DirFiles)\SetupClient.exe' -ArgumentList '/S' -ErrorAction Stop
        # <SPA:CustomCode Phase="Repair" Guide="Enter custom repair script code here (e.g. run repair commands, re-copy pristine files)">
        # TODO: Enter custom repair script code here (e.g. run repair commands, re-copy pristine files)
        # </SPA:CustomCode>

    ##================================================
    ## MARK: Post-Repair
    ##================================================
    $adtSession.InstallPhase = "Post-$($adtSession.DeploymentType)"

        # Raw PowerShell: PowerShell script block
            ##================================================
        
            ## <Perform Post-Installation tasks here>
        
            #Update Uninstall Key
        
             $InstallDate = Get-Date -Format 'yyyyMMdd'
             $InstallSource = Get-Location
        # Raw PowerShell: Control flow block preserved as-is
        If (Test-Path -Path "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Tanium Client") {
             Set-ADTRegistryKey -Key "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Tanium Client" -Name "InstallDate" -Value $InstallDate -Type String
             }
        # Raw PowerShell: Control flow block preserved as-is
        If (Test-Path -Path "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Tanium Client") {
             Set-ADTRegistryKey -Key "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Tanium Client" -Name "InstallSource" -Value $InstallSource -Type String
             }
        Start-Sleep -Seconds 10
        # Raw PowerShell: Control flow block preserved as-is
        if (!$adtSession.UseDefaultMsi)
            {
                Show-ADTInstallationPrompt -Message "$($adtSession.InstallTitle) is installed successfully from your machine." -ButtonRightText 'OK' -Icon Information -NoWait
            }
        # <SPA:CustomCode Phase="Post-Repair" Guide="Enter custom post-repair script code here (e.g. verify repair, log completion)">
        # TODO: Enter custom post-repair script code here (e.g. verify repair, log completion)
        # </SPA:CustomCode>
}


##================================================
## MARK: Initialization
##================================================

$ErrorActionPreference = [System.Management.Automation.ActionPreference]::Stop
$ProgressPreference = [System.Management.Automation.ActionPreference]::SilentlyContinue
Set-StrictMode -Version 1

try
{
    if (Test-Path -LiteralPath "$PSScriptRoot\PSAppDeployToolkit\PSAppDeployToolkit.psd1" -PathType Leaf)
    {
        Get-ChildItem -LiteralPath "$PSScriptRoot\PSAppDeployToolkit" -Recurse -File | Unblock-File -ErrorAction Ignore
        Import-Module -FullyQualifiedName @{ ModuleName = "$PSScriptRoot\PSAppDeployToolkit\PSAppDeployToolkit.psd1"; Guid = '8c3c366b-8606-4576-9f2d-4051144f7ca2'; ModuleVersion = '4.1.0' } -Force
    }
    else
    {
        Import-Module -FullyQualifiedName @{ ModuleName = 'PSAppDeployToolkit'; Guid = '8c3c366b-8606-4576-9f2d-4051144f7ca2'; ModuleVersion = '4.1.0' } -Force
    }

    $iadtParams = Get-ADTBoundParametersAndDefaultValues -Invocation $MyInvocation
    $adtSession = Remove-ADTHashtableNullOrEmptyValues -Hashtable $adtSession
    $adtSession = Open-ADTSession @adtSession @iadtParams -PassThru
}
catch
{
    $Host.UI.WriteErrorLine((Out-String -InputObject $_ -Width ([System.Int32]::MaxValue)))
    exit 60008
}


##================================================
## MARK: Invocation
##================================================

try
{
    Get-ChildItem -LiteralPath $PSScriptRoot -Directory | & {
        process
        {
            if ($_.Name -match 'PSAppDeployToolkit\..+$')
            {
                Get-ChildItem -LiteralPath $_.FullName -Recurse -File | Unblock-File -ErrorAction Ignore
                Import-Module -Name $_.FullName -Force
            }
        }
    }

    & "$($adtSession.DeploymentType)-ADTDeployment"
    Close-ADTSession
}
catch
{
    $mainErrorMessage = "An unhandled error within [$($MyInvocation.MyCommand.Name)] has occurred.`n$(Resolve-ADTErrorRecord -ErrorRecord $_)"
    Write-ADTLogEntry -Message $mainErrorMessage -Severity 3
    Close-ADTSession -ExitCode 60001
}
