<#
.SYNOPSIS
  Converts a lifecycle configuration hashtable to YAML string.

.DESCRIPTION
  Takes the structured hashtable from Invoke-PackagingLifecyclePrompts and
  produces a lifecycle.yaml string suitable for writing to disk. The YAML
  uses snake_case keys matching the lifecycle.schema.json specification.

  This YAML is read at pipeline build time by Build-PsadtFromLifecycle.ps1
  to generate the Invoke-AppDeployToolkit.ps1 script.

.PARAMETER Lifecycle
  Hashtable output from Invoke-PackagingLifecyclePrompts.

.OUTPUTS
  String — the YAML content for lifecycle.yaml.
#>
function ConvertTo-LifecycleYaml {
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory)] [hashtable] $Lifecycle
    )

    $lines = @()
    $lines += "# PSADT v4 Lifecycle Configuration"
    $lines += "# Generated by SPA New-Title scaffolding on $(Get-Date -Format 'yyyy-MM-dd')"
    $lines += "# Edit this file to change install/uninstall behavior."
    $lines += "# The pipeline generates Invoke-AppDeployToolkit.ps1 from this at build time."
    $lines += ""

    # Repair mode
    $repairMode = if ($Lifecycle.RepairMode) { $Lifecycle.RepairMode } else { 'mirror' }
    $lines += "repair_mode: $repairMode"
    $lines += ""

    # Phase mapping: hashtable key → YAML key
    $phases = @(
        @{ Key = 'PreInstall';    YamlKey = 'pre_install';    IsWelcome = $true }
        @{ Key = 'Install';       YamlKey = 'install';        IsWelcome = $false }
        @{ Key = 'PostInstall';   YamlKey = 'post_install';   IsWelcome = $false }
        @{ Key = 'PreUninstall';  YamlKey = 'pre_uninstall';  IsWelcome = $true }
        @{ Key = 'Uninstall';     YamlKey = 'uninstall';      IsWelcome = $false }
        @{ Key = 'PostUninstall'; YamlKey = 'post_uninstall'; IsWelcome = $false }
    )

    # Only emit repair phases when mode is 'custom'
    if ($repairMode -eq 'custom') {
        $phases += @(
            @{ Key = 'PreRepair';  YamlKey = 'pre_repair';  IsWelcome = $true }
            @{ Key = 'Repair';     YamlKey = 'repair';       IsWelcome = $false }
            @{ Key = 'PostRepair'; YamlKey = 'post_repair';  IsWelcome = $false }
        )
    }

    foreach ($phase in $phases) {
        $phaseData = $Lifecycle[$phase.Key]
        if (-not $phaseData) { continue }

        $hasContent = $false
        $phaseLines = @()

        # Welcome-phase properties (close_apps, check_disk_space, allow_defer, show_progress)
        if ($phase.IsWelcome) {
            if ($phaseData.CloseApps) {
                $phaseLines += "  close_apps: `"$($phaseData.CloseApps)`""
                $hasContent = $true
            }
            if ($phaseData.CheckDiskSpace) {
                $phaseLines += "  check_disk_space: true"
                $hasContent = $true
            }
            if ($phaseData.DeferTimes -and $phaseData.DeferTimes -gt 0) {
                $phaseLines += "  allow_defer: $($phaseData.DeferTimes)"
                $hasContent = $true
            }
            # Check for ShowProgress action
            $showProgress = $phaseData.Actions | Where-Object { $_.Type -eq 'ShowProgress' }
            if ($showProgress) {
                $phaseLines += "  show_progress: true"
                $hasContent = $true
            }
        }

        # Actions (exclude CloseApps, CheckDiskSpace, AllowDefer, ShowProgress — they're top-level)
        $actions = @($phaseData.Actions | Where-Object {
            $_.Type -notin @('CloseApps', 'CheckDiskSpace', 'AllowDefer', 'ShowProgress')
        })

        if ($actions.Count -gt 0) {
            $phaseLines += "  actions:"
            $hasContent = $true

            foreach ($action in $actions) {
                $yamlType = ConvertTo-SnakeCase $action.Type
                $phaseLines += "    - type: $yamlType"

                # Emit action-specific properties
                switch ($action.Type) {
                    'MsiInstall' {
                        if ($action.FilePath)     { $phaseLines += "      file_path: `"$($action.FilePath)`"" }
                        if ($action.ArgumentList) { $phaseLines += "      arguments: `"$($action.ArgumentList)`"" }
                    }
                    'ExeInstall' {
                        if ($action.FilePath)     { $phaseLines += "      file_path: `"$($action.FilePath)`"" }
                        if ($action.ArgumentList) { $phaseLines += "      arguments: `"$($action.ArgumentList)`"" }
                    }
                    'MsiUninstall' {
                        if ($action.AppName)     { $phaseLines += "      app_name: `"$($action.AppName)`"" }
                        if ($action.ProductCode) { $phaseLines += "      product_code: `"$($action.ProductCode)`"" }
                    }
                    'ExeUninstall' {
                        if ($action.FilePath)     { $phaseLines += "      file_path: `"$($action.FilePath)`"" }
                        if ($action.ArgumentList) { $phaseLines += "      arguments: `"$($action.ArgumentList)`"" }
                    }
                    'FolderCopy' {
                        if ($action.Source)      { $phaseLines += "      source: `"$($action.Source)`"" }
                        if ($action.Destination) { $phaseLines += "      destination: `"$($action.Destination)`"" }
                    }
                    'FolderRemove' {
                        if ($action.Path) { $phaseLines += "      path: `"$($action.Path)`"" }
                    }
                    'RegistryMarker' {
                        # No extra properties — values come from package.yaml at build time
                    }
                    'RemoveRegistryMarker' {
                        # No extra properties — PackageId comes from package.yaml at build time
                    }
                    'SetRegistryKey' {
                        if ($action.Path)    { $phaseLines += "      path: `"$($action.Path)`"" }
                        if ($action.Name)    { $phaseLines += "      name: `"$($action.Name)`"" }
                        if ($action.RegType) { $phaseLines += "      reg_type: `"$($action.RegType)`"" }
                        if ($action.Value)   { $phaseLines += "      value: `"$($action.Value)`"" }
                    }
                    'RemoveRegistryKey' {
                        if ($action.Path) { $phaseLines += "      path: `"$($action.Path)`"" }
                    }
                    'SetEnvVariable' {
                        if ($action.Name)  { $phaseLines += "      name: `"$($action.Name)`"" }
                        if ($action.Value) { $phaseLines += "      value: `"$($action.Value)`"" }
                    }
                    'RemoveEnvVariable' {
                        if ($action.Name)  { $phaseLines += "      name: `"$($action.Name)`"" }
                        if ($action.Value) { $phaseLines += "      value: `"$($action.Value)`"" }
                    }
                    'ShowCompletion' {
                        # No extra properties
                    }
                    'CustomScript' {
                        if ($action.Path) { $phaseLines += "      script_path: `"$($action.Path)`"" }
                    }
                }
            }
        }

        if ($hasContent) {
            $lines += "$($phase.YamlKey):"
            $lines += $phaseLines
            $lines += ""
        }
    }

    return ($lines -join "`n")
}

function ConvertTo-SnakeCase {
    [OutputType([string])]
    param([string] $PascalCase)
    # MsiInstall → msi_install, RemoveRegistryMarker → remove_registry_marker
    return ($PascalCase -creplace '([A-Z])', '_$1').Trim('_').ToLower()
}
